// Code generated by scripts/schema_models.py from specs/contracts; DO NOT EDIT.

package schema

import (
	"bytes"
	"fmt"

	"encoding/json"
	"github.com/cdot65/prisma-airs-go/aisec"
	"github.com/cdot65/prisma-airs-go/aisec/internal"
)

// BatchAssignCustomRuleRequest represents BatchAssignCustomRuleRequestSchema.
type BatchAssignCustomRuleRequest struct {
	Assignments []CustomRuleAssignment `json:"assignments"`
}

// BatchAssignCustomRuleResponse represents BatchAssignCustomRuleResponseSchema.
type BatchAssignCustomRuleResponse struct {
	Results []CustomRuleAssignmentResult `json:"results"`
}

// ConditionGroupInput represents ConditionGroup.
type ConditionGroupInput struct {
	Conditions []ConditionGroupInputConditionsItem `json:"conditions"`
	Operator   string                              `json:"operator"`
}

// ConditionGroupInputConditionsItem represents ConditionGroupInputConditionsItem.
type ConditionGroupInputConditionsItem json.RawMessage

func (x ConditionGroupInputConditionsItem) MarshalJSON() ([]byte, error) {
	return json.RawMessage(x).MarshalJSON()
}
func (x *ConditionGroupInputConditionsItem) UnmarshalJSON(data []byte) error {
	if !json.Valid(data) {
		return fmt.Errorf("invalid ConditionGroupInputConditionsItem JSON")
	}
	candidate := ConditionGroupInputConditionsItem(data)
	valid := false
	if _, err := candidate.AsLabelCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsRuleResultCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsConditionGroupInput(); err == nil {
		valid = true
	}
	if !valid {
		return fmt.Errorf("no matching ConditionGroupInputConditionsItem alternative")
	}
	*x = append((*x)[:0], data...)
	return nil
}

// AsLabelCondition decodes this union as LabelCondition; tagged variants verify their tag.
func (x ConditionGroupInputConditionsItem) AsLabelCondition() (*LabelCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null ConditionGroupInputConditionsItem alternative")
	}
	var value LabelCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupInputConditionsItem alternative field: type")
	}
	if _, ok := fields["key"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupInputConditionsItem alternative field: key")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupInputConditionsItem alternative field: operator")
	}
	if value.Type != "label" {
		return nil, fmt.Errorf("expected ConditionGroupInputConditionsItem type=%s", "label")
	}
	return &value, nil
}

// NewConditionGroupInputConditionsItemFromLabelCondition encodes the typed union alternative.
func NewConditionGroupInputConditionsItemFromLabelCondition(value LabelCondition) (ConditionGroupInputConditionsItem, error) {
	b, err := json.Marshal(value)
	return ConditionGroupInputConditionsItem(b), err
}

// AsRuleResultCondition decodes this union as RuleResultCondition; tagged variants verify their tag.
func (x ConditionGroupInputConditionsItem) AsRuleResultCondition() (*RuleResultCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null ConditionGroupInputConditionsItem alternative")
	}
	var value RuleResultCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupInputConditionsItem alternative field: type")
	}
	if _, ok := fields["rule_uuid"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupInputConditionsItem alternative field: rule_uuid")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupInputConditionsItem alternative field: operator")
	}
	if _, ok := fields["value"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupInputConditionsItem alternative field: value")
	}
	if value.Operator != "equals" {
		return nil, fmt.Errorf("expected ConditionGroupInputConditionsItem operator=%s", "equals")
	}
	if value.Type != "rule_result" {
		return nil, fmt.Errorf("expected ConditionGroupInputConditionsItem type=%s", "rule_result")
	}
	return &value, nil
}

// NewConditionGroupInputConditionsItemFromRuleResultCondition encodes the typed union alternative.
func NewConditionGroupInputConditionsItemFromRuleResultCondition(value RuleResultCondition) (ConditionGroupInputConditionsItem, error) {
	b, err := json.Marshal(value)
	return ConditionGroupInputConditionsItem(b), err
}

// AsConditionGroupInput decodes this union as ConditionGroupInput; tagged variants verify their tag.
func (x ConditionGroupInputConditionsItem) AsConditionGroupInput() (*ConditionGroupInput, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null ConditionGroupInputConditionsItem alternative")
	}
	var value ConditionGroupInput
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupInputConditionsItem alternative field: operator")
	}
	if _, ok := fields["conditions"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupInputConditionsItem alternative field: conditions")
	}
	return &value, nil
}

// NewConditionGroupInputConditionsItemFromConditionGroupInput encodes the typed union alternative.
func NewConditionGroupInputConditionsItemFromConditionGroupInput(value ConditionGroupInput) (ConditionGroupInputConditionsItem, error) {
	b, err := json.Marshal(value)
	return ConditionGroupInputConditionsItem(b), err
}

// ConditionGroupOutput represents ConditionGroup.
type ConditionGroupOutput struct {
	Conditions []ConditionGroupOutputConditionsItem `json:"conditions"`
	Operator   string                               `json:"operator"`
}

// ConditionGroupOutputConditionsItem represents ConditionGroupOutputConditionsItem.
type ConditionGroupOutputConditionsItem json.RawMessage

func (x ConditionGroupOutputConditionsItem) MarshalJSON() ([]byte, error) {
	return json.RawMessage(x).MarshalJSON()
}
func (x *ConditionGroupOutputConditionsItem) UnmarshalJSON(data []byte) error {
	if !json.Valid(data) {
		return fmt.Errorf("invalid ConditionGroupOutputConditionsItem JSON")
	}
	candidate := ConditionGroupOutputConditionsItem(data)
	valid := false
	if _, err := candidate.AsLabelCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsRuleResultCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsConditionGroupOutput(); err == nil {
		valid = true
	}
	if !valid {
		return fmt.Errorf("no matching ConditionGroupOutputConditionsItem alternative")
	}
	*x = append((*x)[:0], data...)
	return nil
}

// AsLabelCondition decodes this union as LabelCondition; tagged variants verify their tag.
func (x ConditionGroupOutputConditionsItem) AsLabelCondition() (*LabelCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null ConditionGroupOutputConditionsItem alternative")
	}
	var value LabelCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupOutputConditionsItem alternative field: type")
	}
	if _, ok := fields["key"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupOutputConditionsItem alternative field: key")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupOutputConditionsItem alternative field: operator")
	}
	if value.Type != "label" {
		return nil, fmt.Errorf("expected ConditionGroupOutputConditionsItem type=%s", "label")
	}
	return &value, nil
}

// NewConditionGroupOutputConditionsItemFromLabelCondition encodes the typed union alternative.
func NewConditionGroupOutputConditionsItemFromLabelCondition(value LabelCondition) (ConditionGroupOutputConditionsItem, error) {
	b, err := json.Marshal(value)
	return ConditionGroupOutputConditionsItem(b), err
}

// AsRuleResultCondition decodes this union as RuleResultCondition; tagged variants verify their tag.
func (x ConditionGroupOutputConditionsItem) AsRuleResultCondition() (*RuleResultCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null ConditionGroupOutputConditionsItem alternative")
	}
	var value RuleResultCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupOutputConditionsItem alternative field: type")
	}
	if _, ok := fields["rule_uuid"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupOutputConditionsItem alternative field: rule_uuid")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupOutputConditionsItem alternative field: operator")
	}
	if _, ok := fields["value"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupOutputConditionsItem alternative field: value")
	}
	if value.Operator != "equals" {
		return nil, fmt.Errorf("expected ConditionGroupOutputConditionsItem operator=%s", "equals")
	}
	if value.Type != "rule_result" {
		return nil, fmt.Errorf("expected ConditionGroupOutputConditionsItem type=%s", "rule_result")
	}
	return &value, nil
}

// NewConditionGroupOutputConditionsItemFromRuleResultCondition encodes the typed union alternative.
func NewConditionGroupOutputConditionsItemFromRuleResultCondition(value RuleResultCondition) (ConditionGroupOutputConditionsItem, error) {
	b, err := json.Marshal(value)
	return ConditionGroupOutputConditionsItem(b), err
}

// AsConditionGroupOutput decodes this union as ConditionGroupOutput; tagged variants verify their tag.
func (x ConditionGroupOutputConditionsItem) AsConditionGroupOutput() (*ConditionGroupOutput, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null ConditionGroupOutputConditionsItem alternative")
	}
	var value ConditionGroupOutput
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupOutputConditionsItem alternative field: operator")
	}
	if _, ok := fields["conditions"]; !ok {
		return nil, fmt.Errorf("missing ConditionGroupOutputConditionsItem alternative field: conditions")
	}
	return &value, nil
}

// NewConditionGroupOutputConditionsItemFromConditionGroupOutput encodes the typed union alternative.
func NewConditionGroupOutputConditionsItemFromConditionGroupOutput(value ConditionGroupOutput) (ConditionGroupOutputConditionsItem, error) {
	b, err := json.Marshal(value)
	return ConditionGroupOutputConditionsItem(b), err
}

// CursorPagination represents CursorPaginationSchema.
type CursorPagination struct {
	NextToken aisec.Optional[string] `json:"next_token,omitempty"`
}

func (x CursorPagination) MarshalJSON() ([]byte, error) {
	type alias CursorPagination
	return internal.MarshalOptionalFields(alias(x))
}

// CustomRuleAssignment represents CustomRuleAssignmentSchema.
type CustomRuleAssignment struct {
	SecurityGroupUUID string    `json:"security_group_uuid"`
	State             RuleState `json:"state"`
}

// CustomRuleAssignmentResult represents CustomRuleAssignmentResultSchema.
type CustomRuleAssignmentResult struct {
	Error             aisec.Optional[string] `json:"error,omitempty"`
	RuleInstanceUUID  aisec.Optional[string] `json:"rule_instance_uuid,omitempty"`
	SecurityGroupUUID string                 `json:"security_group_uuid"`
	Status            string                 `json:"status"`
}

func (x CustomRuleAssignmentResult) MarshalJSON() ([]byte, error) {
	type alias CustomRuleAssignmentResult
	return internal.MarshalOptionalFields(alias(x))
}

// CustomRuleCreateRequest represents CustomRuleCreateRequestSchema.
type CustomRuleCreateRequest struct {
	CompatibleSources  []SourceType                     `json:"compatible_sources"`
	Condition          CustomRuleCreateRequestCondition `json:"condition"`
	Description        *string                          `json:"description,omitempty"`
	Name               string                           `json:"name"`
	RemediationMessage aisec.Optional[string]           `json:"remediation_message,omitempty"`
	RuleAction         *string                          `json:"rule_action,omitempty"`
	ViolationMessage   string                           `json:"violation_message"`
}

func (x CustomRuleCreateRequest) MarshalJSON() ([]byte, error) {
	type alias CustomRuleCreateRequest
	return internal.MarshalOptionalFields(alias(x))
}

// CustomRuleCreateRequestCondition represents Condition.
type CustomRuleCreateRequestCondition json.RawMessage

func (x CustomRuleCreateRequestCondition) MarshalJSON() ([]byte, error) {
	return json.RawMessage(x).MarshalJSON()
}
func (x *CustomRuleCreateRequestCondition) UnmarshalJSON(data []byte) error {
	if !json.Valid(data) {
		return fmt.Errorf("invalid CustomRuleCreateRequestCondition JSON")
	}
	candidate := CustomRuleCreateRequestCondition(data)
	valid := false
	if _, err := candidate.AsLabelCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsRuleResultCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsConditionGroupInput(); err == nil {
		valid = true
	}
	if !valid {
		return fmt.Errorf("no matching CustomRuleCreateRequestCondition alternative")
	}
	*x = append((*x)[:0], data...)
	return nil
}

// AsLabelCondition decodes this union as LabelCondition; tagged variants verify their tag.
func (x CustomRuleCreateRequestCondition) AsLabelCondition() (*LabelCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleCreateRequestCondition alternative")
	}
	var value LabelCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleCreateRequestCondition alternative field: type")
	}
	if _, ok := fields["key"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleCreateRequestCondition alternative field: key")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleCreateRequestCondition alternative field: operator")
	}
	if value.Type != "label" {
		return nil, fmt.Errorf("expected CustomRuleCreateRequestCondition type=%s", "label")
	}
	return &value, nil
}

// NewCustomRuleCreateRequestConditionFromLabelCondition encodes the typed union alternative.
func NewCustomRuleCreateRequestConditionFromLabelCondition(value LabelCondition) (CustomRuleCreateRequestCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleCreateRequestCondition(b), err
}

// AsRuleResultCondition decodes this union as RuleResultCondition; tagged variants verify their tag.
func (x CustomRuleCreateRequestCondition) AsRuleResultCondition() (*RuleResultCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleCreateRequestCondition alternative")
	}
	var value RuleResultCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleCreateRequestCondition alternative field: type")
	}
	if _, ok := fields["rule_uuid"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleCreateRequestCondition alternative field: rule_uuid")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleCreateRequestCondition alternative field: operator")
	}
	if _, ok := fields["value"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleCreateRequestCondition alternative field: value")
	}
	if value.Operator != "equals" {
		return nil, fmt.Errorf("expected CustomRuleCreateRequestCondition operator=%s", "equals")
	}
	if value.Type != "rule_result" {
		return nil, fmt.Errorf("expected CustomRuleCreateRequestCondition type=%s", "rule_result")
	}
	return &value, nil
}

// NewCustomRuleCreateRequestConditionFromRuleResultCondition encodes the typed union alternative.
func NewCustomRuleCreateRequestConditionFromRuleResultCondition(value RuleResultCondition) (CustomRuleCreateRequestCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleCreateRequestCondition(b), err
}

// AsConditionGroupInput decodes this union as ConditionGroupInput; tagged variants verify their tag.
func (x CustomRuleCreateRequestCondition) AsConditionGroupInput() (*ConditionGroupInput, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleCreateRequestCondition alternative")
	}
	var value ConditionGroupInput
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleCreateRequestCondition alternative field: operator")
	}
	if _, ok := fields["conditions"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleCreateRequestCondition alternative field: conditions")
	}
	return &value, nil
}

// NewCustomRuleCreateRequestConditionFromConditionGroupInput encodes the typed union alternative.
func NewCustomRuleCreateRequestConditionFromConditionGroupInput(value ConditionGroupInput) (CustomRuleCreateRequestCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleCreateRequestCondition(b), err
}

// CustomRuleInstanceSummary represents Lightweight custom rule info nested in rule instance responses.
type CustomRuleInstanceSummary struct {
	Description string `json:"description"`
	Name        string `json:"name"`
	UUID        string `json:"uuid"`
}

// CustomRuleListItem represents CustomRuleListItemSchema.
type CustomRuleListItem struct {
	CompatibleSources []SourceType `json:"compatible_sources"`
	// The rule's condition tree. Null when reading a historical snapshot (via ?generation=N): the snapshot stores only the compiled policy, not the source condition.
	Condition aisec.Optional[CustomRuleListItemCondition] `json:"condition,omitempty"`
	// When the rule was created. Null when reading a historical snapshot (via ?generation=N), which does not capture this timestamp.
	CreatedAt   aisec.Optional[string] `json:"created_at,omitempty"`
	CreatedBy   *string                `json:"created_by"`
	Description string                 `json:"description"`
	// Number of security groups that currently have this rule enabled. Null when reading a historical snapshot (via ?generation=N), since the count is a live value not captured in the snapshot.
	EnabledSecurityGroupCount aisec.Optional[int64] `json:"enabled_security_group_count,omitempty"`
	IsArchived                bool                  `json:"is_archived"`
	Name                      string                `json:"name"`
	RemediationMessage        *string               `json:"remediation_message"`
	// The rule's action. Null when reading a historical snapshot (via ?generation=N): it is compiled into the policy and not carried in the snapshot.
	RuleAction aisec.Optional[string] `json:"rule_action,omitempty"`
	TSGID      string                 `json:"tsg_id"`
	// When the rule was last updated. Null when reading a historical snapshot (via ?generation=N), which does not capture this timestamp.
	UpdatedAt        aisec.Optional[string] `json:"updated_at,omitempty"`
	UpdatedBy        *string                `json:"updated_by"`
	UUID             string                 `json:"uuid"`
	ViolationMessage string                 `json:"violation_message"`
}

func (x CustomRuleListItem) MarshalJSON() ([]byte, error) {
	type alias CustomRuleListItem
	return internal.MarshalOptionalFields(alias(x))
}

// CustomRuleListItemCondition represents The rule's condition tree. Null when reading a historical snapshot (via ?generation=N): the snapshot stores only the compiled policy, not the source condition..
type CustomRuleListItemCondition json.RawMessage

func (x CustomRuleListItemCondition) MarshalJSON() ([]byte, error) {
	return json.RawMessage(x).MarshalJSON()
}
func (x *CustomRuleListItemCondition) UnmarshalJSON(data []byte) error {
	if !json.Valid(data) {
		return fmt.Errorf("invalid CustomRuleListItemCondition JSON")
	}
	candidate := CustomRuleListItemCondition(data)
	valid := false
	if _, err := candidate.AsLabelCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsRuleResultCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsConditionGroupOutput(); err == nil {
		valid = true
	}
	if !valid {
		return fmt.Errorf("no matching CustomRuleListItemCondition alternative")
	}
	*x = append((*x)[:0], data...)
	return nil
}

// AsLabelCondition decodes this union as LabelCondition; tagged variants verify their tag.
func (x CustomRuleListItemCondition) AsLabelCondition() (*LabelCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleListItemCondition alternative")
	}
	var value LabelCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleListItemCondition alternative field: type")
	}
	if _, ok := fields["key"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleListItemCondition alternative field: key")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleListItemCondition alternative field: operator")
	}
	if value.Type != "label" {
		return nil, fmt.Errorf("expected CustomRuleListItemCondition type=%s", "label")
	}
	return &value, nil
}

// NewCustomRuleListItemConditionFromLabelCondition encodes the typed union alternative.
func NewCustomRuleListItemConditionFromLabelCondition(value LabelCondition) (CustomRuleListItemCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleListItemCondition(b), err
}

// AsRuleResultCondition decodes this union as RuleResultCondition; tagged variants verify their tag.
func (x CustomRuleListItemCondition) AsRuleResultCondition() (*RuleResultCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleListItemCondition alternative")
	}
	var value RuleResultCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleListItemCondition alternative field: type")
	}
	if _, ok := fields["rule_uuid"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleListItemCondition alternative field: rule_uuid")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleListItemCondition alternative field: operator")
	}
	if _, ok := fields["value"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleListItemCondition alternative field: value")
	}
	if value.Operator != "equals" {
		return nil, fmt.Errorf("expected CustomRuleListItemCondition operator=%s", "equals")
	}
	if value.Type != "rule_result" {
		return nil, fmt.Errorf("expected CustomRuleListItemCondition type=%s", "rule_result")
	}
	return &value, nil
}

// NewCustomRuleListItemConditionFromRuleResultCondition encodes the typed union alternative.
func NewCustomRuleListItemConditionFromRuleResultCondition(value RuleResultCondition) (CustomRuleListItemCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleListItemCondition(b), err
}

// AsConditionGroupOutput decodes this union as ConditionGroupOutput; tagged variants verify their tag.
func (x CustomRuleListItemCondition) AsConditionGroupOutput() (*ConditionGroupOutput, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleListItemCondition alternative")
	}
	var value ConditionGroupOutput
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleListItemCondition alternative field: operator")
	}
	if _, ok := fields["conditions"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleListItemCondition alternative field: conditions")
	}
	return &value, nil
}

// NewCustomRuleListItemConditionFromConditionGroupOutput encodes the typed union alternative.
func NewCustomRuleListItemConditionFromConditionGroupOutput(value ConditionGroupOutput) (CustomRuleListItemCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleListItemCondition(b), err
}

// CustomRuleResponse represents CustomRuleResponseSchema.
type CustomRuleResponse struct {
	CompatibleSources []SourceType `json:"compatible_sources"`
	// The rule's condition tree. Null when reading a historical snapshot (via ?generation=N): the snapshot stores only the compiled policy, not the source condition.
	Condition aisec.Optional[CustomRuleResponseCondition] `json:"condition,omitempty"`
	// When the rule was created. Null when reading a historical snapshot (via ?generation=N), which does not capture this timestamp.
	CreatedAt          aisec.Optional[string] `json:"created_at,omitempty"`
	CreatedBy          *string                `json:"created_by"`
	Description        string                 `json:"description"`
	IsArchived         bool                   `json:"is_archived"`
	Name               string                 `json:"name"`
	RemediationMessage *string                `json:"remediation_message"`
	// The rule's action. Null when reading a historical snapshot (via ?generation=N): it is compiled into the policy and not carried in the snapshot.
	RuleAction aisec.Optional[string] `json:"rule_action,omitempty"`
	TSGID      string                 `json:"tsg_id"`
	// When the rule was last updated. Null when reading a historical snapshot (via ?generation=N), which does not capture this timestamp.
	UpdatedAt        aisec.Optional[string] `json:"updated_at,omitempty"`
	UpdatedBy        *string                `json:"updated_by"`
	UUID             string                 `json:"uuid"`
	ViolationMessage string                 `json:"violation_message"`
}

func (x CustomRuleResponse) MarshalJSON() ([]byte, error) {
	type alias CustomRuleResponse
	return internal.MarshalOptionalFields(alias(x))
}

// CustomRuleResponseCondition represents The rule's condition tree. Null when reading a historical snapshot (via ?generation=N): the snapshot stores only the compiled policy, not the source condition..
type CustomRuleResponseCondition json.RawMessage

func (x CustomRuleResponseCondition) MarshalJSON() ([]byte, error) {
	return json.RawMessage(x).MarshalJSON()
}
func (x *CustomRuleResponseCondition) UnmarshalJSON(data []byte) error {
	if !json.Valid(data) {
		return fmt.Errorf("invalid CustomRuleResponseCondition JSON")
	}
	candidate := CustomRuleResponseCondition(data)
	valid := false
	if _, err := candidate.AsLabelCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsRuleResultCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsConditionGroupOutput(); err == nil {
		valid = true
	}
	if !valid {
		return fmt.Errorf("no matching CustomRuleResponseCondition alternative")
	}
	*x = append((*x)[:0], data...)
	return nil
}

// AsLabelCondition decodes this union as LabelCondition; tagged variants verify their tag.
func (x CustomRuleResponseCondition) AsLabelCondition() (*LabelCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleResponseCondition alternative")
	}
	var value LabelCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleResponseCondition alternative field: type")
	}
	if _, ok := fields["key"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleResponseCondition alternative field: key")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleResponseCondition alternative field: operator")
	}
	if value.Type != "label" {
		return nil, fmt.Errorf("expected CustomRuleResponseCondition type=%s", "label")
	}
	return &value, nil
}

// NewCustomRuleResponseConditionFromLabelCondition encodes the typed union alternative.
func NewCustomRuleResponseConditionFromLabelCondition(value LabelCondition) (CustomRuleResponseCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleResponseCondition(b), err
}

// AsRuleResultCondition decodes this union as RuleResultCondition; tagged variants verify their tag.
func (x CustomRuleResponseCondition) AsRuleResultCondition() (*RuleResultCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleResponseCondition alternative")
	}
	var value RuleResultCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleResponseCondition alternative field: type")
	}
	if _, ok := fields["rule_uuid"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleResponseCondition alternative field: rule_uuid")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleResponseCondition alternative field: operator")
	}
	if _, ok := fields["value"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleResponseCondition alternative field: value")
	}
	if value.Operator != "equals" {
		return nil, fmt.Errorf("expected CustomRuleResponseCondition operator=%s", "equals")
	}
	if value.Type != "rule_result" {
		return nil, fmt.Errorf("expected CustomRuleResponseCondition type=%s", "rule_result")
	}
	return &value, nil
}

// NewCustomRuleResponseConditionFromRuleResultCondition encodes the typed union alternative.
func NewCustomRuleResponseConditionFromRuleResultCondition(value RuleResultCondition) (CustomRuleResponseCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleResponseCondition(b), err
}

// AsConditionGroupOutput decodes this union as ConditionGroupOutput; tagged variants verify their tag.
func (x CustomRuleResponseCondition) AsConditionGroupOutput() (*ConditionGroupOutput, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleResponseCondition alternative")
	}
	var value ConditionGroupOutput
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleResponseCondition alternative field: operator")
	}
	if _, ok := fields["conditions"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleResponseCondition alternative field: conditions")
	}
	return &value, nil
}

// NewCustomRuleResponseConditionFromConditionGroupOutput encodes the typed union alternative.
func NewCustomRuleResponseConditionFromConditionGroupOutput(value ConditionGroupOutput) (CustomRuleResponseCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleResponseCondition(b), err
}

// CustomRuleSecurityGroup represents CustomRuleSecurityGroupSchema.
type CustomRuleSecurityGroup struct {
	Name       string     `json:"name"`
	RuleState  RuleState  `json:"rule_state"`
	SourceType SourceType `json:"source_type"`
	UUID       string     `json:"uuid"`
}

// CustomRuleUpdateRequest represents CustomRuleUpdateRequestSchema.
type CustomRuleUpdateRequest struct {
	Condition          aisec.Optional[CustomRuleUpdateRequestCondition] `json:"condition,omitempty"`
	Description        aisec.Optional[string]                           `json:"description,omitempty"`
	Name               aisec.Optional[string]                           `json:"name,omitempty"`
	RemediationMessage aisec.Optional[string]                           `json:"remediation_message,omitempty"`
	RuleAction         aisec.Optional[string]                           `json:"rule_action,omitempty"`
	ViolationMessage   aisec.Optional[string]                           `json:"violation_message,omitempty"`
}

func (x CustomRuleUpdateRequest) MarshalJSON() ([]byte, error) {
	type alias CustomRuleUpdateRequest
	return internal.MarshalOptionalFields(alias(x))
}

// CustomRuleUpdateRequestCondition represents Condition.
type CustomRuleUpdateRequestCondition json.RawMessage

func (x CustomRuleUpdateRequestCondition) MarshalJSON() ([]byte, error) {
	return json.RawMessage(x).MarshalJSON()
}
func (x *CustomRuleUpdateRequestCondition) UnmarshalJSON(data []byte) error {
	if !json.Valid(data) {
		return fmt.Errorf("invalid CustomRuleUpdateRequestCondition JSON")
	}
	candidate := CustomRuleUpdateRequestCondition(data)
	valid := false
	if _, err := candidate.AsLabelCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsRuleResultCondition(); err == nil {
		valid = true
	}
	if _, err := candidate.AsConditionGroupInput(); err == nil {
		valid = true
	}
	if !valid {
		return fmt.Errorf("no matching CustomRuleUpdateRequestCondition alternative")
	}
	*x = append((*x)[:0], data...)
	return nil
}

// AsLabelCondition decodes this union as LabelCondition; tagged variants verify their tag.
func (x CustomRuleUpdateRequestCondition) AsLabelCondition() (*LabelCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleUpdateRequestCondition alternative")
	}
	var value LabelCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleUpdateRequestCondition alternative field: type")
	}
	if _, ok := fields["key"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleUpdateRequestCondition alternative field: key")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleUpdateRequestCondition alternative field: operator")
	}
	if value.Type != "label" {
		return nil, fmt.Errorf("expected CustomRuleUpdateRequestCondition type=%s", "label")
	}
	return &value, nil
}

// NewCustomRuleUpdateRequestConditionFromLabelCondition encodes the typed union alternative.
func NewCustomRuleUpdateRequestConditionFromLabelCondition(value LabelCondition) (CustomRuleUpdateRequestCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleUpdateRequestCondition(b), err
}

// AsRuleResultCondition decodes this union as RuleResultCondition; tagged variants verify their tag.
func (x CustomRuleUpdateRequestCondition) AsRuleResultCondition() (*RuleResultCondition, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleUpdateRequestCondition alternative")
	}
	var value RuleResultCondition
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["type"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleUpdateRequestCondition alternative field: type")
	}
	if _, ok := fields["rule_uuid"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleUpdateRequestCondition alternative field: rule_uuid")
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleUpdateRequestCondition alternative field: operator")
	}
	if _, ok := fields["value"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleUpdateRequestCondition alternative field: value")
	}
	if value.Operator != "equals" {
		return nil, fmt.Errorf("expected CustomRuleUpdateRequestCondition operator=%s", "equals")
	}
	if value.Type != "rule_result" {
		return nil, fmt.Errorf("expected CustomRuleUpdateRequestCondition type=%s", "rule_result")
	}
	return &value, nil
}

// NewCustomRuleUpdateRequestConditionFromRuleResultCondition encodes the typed union alternative.
func NewCustomRuleUpdateRequestConditionFromRuleResultCondition(value RuleResultCondition) (CustomRuleUpdateRequestCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleUpdateRequestCondition(b), err
}

// AsConditionGroupInput decodes this union as ConditionGroupInput; tagged variants verify their tag.
func (x CustomRuleUpdateRequestCondition) AsConditionGroupInput() (*ConditionGroupInput, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null CustomRuleUpdateRequestCondition alternative")
	}
	var value ConditionGroupInput
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(x, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["operator"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleUpdateRequestCondition alternative field: operator")
	}
	if _, ok := fields["conditions"]; !ok {
		return nil, fmt.Errorf("missing CustomRuleUpdateRequestCondition alternative field: conditions")
	}
	return &value, nil
}

// NewCustomRuleUpdateRequestConditionFromConditionGroupInput encodes the typed union alternative.
func NewCustomRuleUpdateRequestConditionFromConditionGroupInput(value ConditionGroupInput) (CustomRuleUpdateRequestCondition, error) {
	b, err := json.Marshal(value)
	return CustomRuleUpdateRequestCondition(b), err
}

// ErrorCodes represents ErrorCodes.
type ErrorCodes string

const (
	ErrorCodesUnknownError              ErrorCodes = "UNKNOWN_ERROR"
	ErrorCodesScanError                 ErrorCodes = "SCAN_ERROR"
	ErrorCodesInvalidResponse           ErrorCodes = "INVALID_RESPONSE"
	ErrorCodesAccessDenied              ErrorCodes = "ACCESS_DENIED"
	ErrorCodesMissingCredentials        ErrorCodes = "MISSING_CREDENTIALS"
	ErrorCodesNoSuchKey                 ErrorCodes = "NO_SUCH_KEY"
	ErrorCodesNoSuchBucket              ErrorCodes = "NO_SUCH_BUCKET"
	ErrorCodesInvalidBucketName         ErrorCodes = "INVALID_BUCKET_NAME"
	ErrorCodesInternalError             ErrorCodes = "INTERNAL_ERROR"
	ErrorCodesServiceUnavailable        ErrorCodes = "SERVICE_UNAVAILABLE"
	ErrorCodesInvalidObjectState        ErrorCodes = "INVALID_OBJECT_STATE"
	ErrorCodesUnknownRemoteServiceError ErrorCodes = "UNKNOWN_REMOTE_SERVICE_ERROR"
	ErrorCodesUnsupportedRemoteStorage  ErrorCodes = "UNSUPPORTED_REMOTE_STORAGE"
	ErrorCodesMissingArtifacts          ErrorCodes = "MISSING_ARTIFACTS"
	ErrorCodesWorkerError               ErrorCodes = "WORKER_ERROR"
	ErrorCodesPolicyEvalError           ErrorCodes = "POLICY_EVAL_ERROR"
	ErrorCodesResourceNotFound          ErrorCodes = "RESOURCE_NOT_FOUND"
	ErrorCodesScanDataPending           ErrorCodes = "SCAN_DATA_PENDING"
)

// EvalOutcome represents EvalOutcome.
type EvalOutcome string

const (
	EvalOutcomePending EvalOutcome = "PENDING"
	EvalOutcomeAllowed EvalOutcome = "ALLOWED"
	EvalOutcomeBlocked EvalOutcome = "BLOCKED"
	EvalOutcomeError   EvalOutcome = "ERROR"
)

// EvalSummary represents EvalSummarySchema.
type EvalSummary struct {
	RulesFailed *int64 `json:"rules_failed,omitempty"`
	RulesPassed *int64 `json:"rules_passed,omitempty"`
	TotalRules  *int64 `json:"total_rules,omitempty"`
}

// FileList represents Schema for file list responses..
type FileList struct {
	Files      []FileResponse `json:"files"`
	Pagination Pagination     `json:"pagination"`
}

// FileResponse represents Schema for file response details..
type FileResponse struct {
	BlobID           aisec.Optional[string]   `json:"blob_id,omitempty"`
	CreatedAt        string                   `json:"created_at"`
	Formats          aisec.Optional[[]string] `json:"formats,omitempty"`
	ModelVersionUUID string                   `json:"model_version_uuid"`
	ParentPath       string                   `json:"parent_path"`
	Path             string                   `json:"path"`
	Result           FileScanResult           `json:"result"`
	ScanUUID         aisec.Optional[string]   `json:"scan_uuid,omitempty"`
	TSGID            string                   `json:"tsg_id"`
	Type             FileType                 `json:"type"`
	UpdatedAt        string                   `json:"updated_at"`
	UUID             string                   `json:"uuid"`
}

func (x FileResponse) MarshalJSON() ([]byte, error) {
	type alias FileResponse
	return internal.MarshalOptionalFields(alias(x))
}

// FileScanData represents FileScanDataSchema.
type FileScanData struct {
	BlobID          string                           `json:"blob_id"`
	ErrorMessage    aisec.Optional[string]           `json:"error_message,omitempty"`
	FilePath        string                           `json:"file_path"`
	Formats         aisec.Optional[[]string]         `json:"formats,omitempty"`
	IssuesDetected  aisec.Optional[[]ModelScanIssue] `json:"issues_detected,omitempty"`
	ModelscanStatus ModelScanStatus                  `json:"modelscan_status"`
	SHA256          aisec.Optional[string]           `json:"sha256,omitempty"`
	SizeBytes       aisec.Optional[int64]            `json:"size_bytes,omitempty"`
}

func (x FileScanData) MarshalJSON() ([]byte, error) {
	type alias FileScanData
	return internal.MarshalOptionalFields(alias(x))
}

// FileScanResult represents Results of individual file scanning..
type FileScanResult string

const (
	FileScanResultSkipped FileScanResult = "SKIPPED"
	FileScanResultSuccess FileScanResult = "SUCCESS"
	FileScanResultError   FileScanResult = "ERROR"
	FileScanResultFailed  FileScanResult = "FAILED"
)

// FileType represents FileType.
type FileType string

const (
	FileTypeDirectory FileType = "DIRECTORY"
	FileTypeFile      FileType = "FILE"
)

// HTTPValidationError represents HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// Label represents LabelSchema.
type Label struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// LabelCondition represents LabelCondition.
type LabelCondition struct {
	Key      string                 `json:"key"`
	Operator string                 `json:"operator"`
	Type     string                 `json:"type"`
	Value    aisec.Optional[string] `json:"value,omitempty"`
}

func (x LabelCondition) MarshalJSON() ([]byte, error) {
	type alias LabelCondition
	return internal.MarshalOptionalFields(alias(x))
}

// LabelKeyList represents LabelKeyListSchema.
type LabelKeyList struct {
	Keys       []string   `json:"keys"`
	Pagination Pagination `json:"pagination"`
}

// LabelValueList represents LabelValueListSchema.
type LabelValueList struct {
	Pagination Pagination `json:"pagination"`
	Values     []string   `json:"values"`
}

// LabelsCreateRequest represents LabelsCreateRequestSchema.
type LabelsCreateRequest struct {
	Labels []Label `json:"labels"`
}

// LabelsResponse represents LabelsResponseSchema.
type LabelsResponse map[string]any

// ListCustomRuleSecurityGroupsResponse represents ListCustomRuleSecurityGroupsResponseSchema.
type ListCustomRuleSecurityGroupsResponse struct {
	Pagination     Pagination                `json:"pagination"`
	SecurityGroups []CustomRuleSecurityGroup `json:"security_groups"`
}

// ListCustomRulesResponse represents ListCustomRulesResponseSchema.
type ListCustomRulesResponse struct {
	CustomRules []CustomRuleListItem `json:"custom_rules"`
	Pagination  Pagination           `json:"pagination"`
}

// ListModelSecurityGroupsResponse represents ListModelSecurityGroupsResponseSchema.
type ListModelSecurityGroupsResponse struct {
	Pagination     Pagination                   `json:"pagination"`
	SecurityGroups []ModelSecurityGroupListItem `json:"security_groups"`
}

// ListModelSecurityRuleInstancesResponse represents ListModelSecurityRuleInstancesResponseSchema.
type ListModelSecurityRuleInstancesResponse struct {
	Pagination    Pagination                          `json:"pagination"`
	RuleInstances []ModelSecurityRuleInstanceResponse `json:"rule_instances"`
}

// ListModelSecurityRulesResponse represents ListModelSecurityRulesResponseSchema.
type ListModelSecurityRulesResponse struct {
	Pagination Pagination                  `json:"pagination"`
	Rules      []ModelSecurityRuleListItem `json:"rules"`
}

// ModelList represents Schema for listing models..
type ModelList struct {
	Models     []ModelResponse `json:"models"`
	Pagination Pagination      `json:"pagination"`
}

// ModelResponse represents Schema for model responses..
type ModelResponse struct {
	CreatedAt                string                       `json:"created_at"`
	LatestVersionFingerprint aisec.Optional[string]       `json:"latest_version_fingerprint,omitempty"`
	LatestVersionFormats     aisec.Optional[[]string]     `json:"latest_version_formats,omitempty"`
	LatestVersionHfCommitSha aisec.Optional[string]       `json:"latest_version_hf_commit_sha,omitempty"`
	LatestVersionOutcome     aisec.Optional[EvalOutcome]  `json:"latest_version_outcome,omitempty"`
	LatestVersionRevision    aisec.Optional[string]       `json:"latest_version_revision,omitempty"`
	LatestVersionScanTime    aisec.Optional[string]       `json:"latest_version_scan_time,omitempty"`
	LatestVersionSourceTypes aisec.Optional[[]SourceType] `json:"latest_version_source_types,omitempty"`
	LatestVersionUUID        aisec.Optional[string]       `json:"latest_version_uuid,omitempty"`
	Name                     string                       `json:"name"`
	TSGID                    string                       `json:"tsg_id"`
	UpdatedAt                string                       `json:"updated_at"`
	UUID                     string                       `json:"uuid"`
}

func (x ModelResponse) MarshalJSON() ([]byte, error) {
	type alias ModelResponse
	return internal.MarshalOptionalFields(alias(x))
}

// ModelScanIssue represents ModelScanIssue.
type ModelScanIssue struct {
	Description string                         `json:"description"`
	Module      aisec.Optional[string]         `json:"module,omitempty"`
	Operator    aisec.Optional[string]         `json:"operator,omitempty"`
	Source      string                         `json:"source"`
	Threat      aisec.Optional[ThreatCategory] `json:"threat,omitempty"`
}

func (x ModelScanIssue) MarshalJSON() ([]byte, error) {
	type alias ModelScanIssue
	return internal.MarshalOptionalFields(alias(x))
}

// ModelScanStatus represents ModelScanStatus.
type ModelScanStatus string

const (
	ModelScanStatusScanned ModelScanStatus = "SCANNED"
	ModelScanStatusSkipped ModelScanStatus = "SKIPPED"
	ModelScanStatusError   ModelScanStatus = "ERROR"
)

// ModelSecurityGroupCreateRequest represents ModelSecurityGroupCreateRequestSchema.
type ModelSecurityGroupCreateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	// Keys in this dictionary should be rule UUIDs to customize upon creation of the model security group.
	RuleConfigurations *map[string]RuleConfiguration `json:"rule_configurations,omitempty"`
	SourceType         SourceType                    `json:"source_type"`
}

// ModelSecurityGroupListItem represents ModelSecurityGroupListItemSchema.
type ModelSecurityGroupListItem struct {
	CreatedAt        string `json:"created_at"`
	Description      string `json:"description"`
	EnabledRuleCount *int64 `json:"enabled_rule_count,omitempty"`
	// Indicates whether this security group is deleted
	IsTombstone bool                    `json:"is_tombstone"`
	Name        string                  `json:"name"`
	SourceType  SourceType              `json:"source_type"`
	State       ModelSecurityGroupState `json:"state"`
	TSGID       string                  `json:"tsg_id"`
	UpdatedAt   string                  `json:"updated_at"`
	UUID        string                  `json:"uuid"`
}

// ModelSecurityGroupResponse represents ModelSecurityGroupResponseSchema.
type ModelSecurityGroupResponse struct {
	CreatedAt   string `json:"created_at"`
	Description string `json:"description"`
	// Indicates whether this security group is deleted
	IsTombstone bool                    `json:"is_tombstone"`
	Name        string                  `json:"name"`
	SourceType  SourceType              `json:"source_type"`
	State       ModelSecurityGroupState `json:"state"`
	TSGID       string                  `json:"tsg_id"`
	UpdatedAt   string                  `json:"updated_at"`
	UUID        string                  `json:"uuid"`
}

// ModelSecurityGroupState represents Security group states..
type ModelSecurityGroupState string

const (
	ModelSecurityGroupStatePending ModelSecurityGroupState = "PENDING"
	ModelSecurityGroupStateActive  ModelSecurityGroupState = "ACTIVE"
)

// ModelSecurityGroupUpdateRequest represents ModelSecurityGroupUpdateRequestSchema.
type ModelSecurityGroupUpdateRequest struct {
	Description aisec.Optional[string] `json:"description,omitempty"`
	Name        aisec.Optional[string] `json:"name,omitempty"`
}

func (x ModelSecurityGroupUpdateRequest) MarshalJSON() ([]byte, error) {
	type alias ModelSecurityGroupUpdateRequest
	return internal.MarshalOptionalFields(alias(x))
}

// ModelSecurityRuleInstanceResponse represents Instantiated rule schema - actual rules that get evaluated.
type ModelSecurityRuleInstanceResponse struct {
	// When the rule instance was created. Null when reading a historical snapshot (via ?generation=N), which does not capture this timestamp.
	CreatedAt      aisec.Optional[string]                    `json:"created_at,omitempty"`
	CreatedBy      aisec.Optional[string]                    `json:"created_by,omitempty"`
	CustomRule     aisec.Optional[CustomRuleInstanceSummary] `json:"custom_rule,omitempty"`
	CustomRuleUUID aisec.Optional[string]                    `json:"custom_rule_uuid,omitempty"`
	// Dictionary for configuring policies custom settings to applicable policies. Allowed keys are approved_formats, approved_locations, approved_licenses, deny_orgs, and denied_org_models. Values should be a list of strings.
	FieldValues       *map[string]any                           `json:"field_values,omitempty"`
	Rule              aisec.Optional[ModelSecurityRuleResponse] `json:"rule,omitempty"`
	SecurityGroupUUID string                                    `json:"security_group_uuid"`
	SecurityRuleUUID  aisec.Optional[string]                    `json:"security_rule_uuid,omitempty"`
	State             RuleState                                 `json:"state"`
	TSGID             string                                    `json:"tsg_id"`
	// When the rule instance was last updated. Null when reading a historical snapshot (via ?generation=N), which does not capture this timestamp.
	UpdatedAt aisec.Optional[string] `json:"updated_at,omitempty"`
	UpdatedBy aisec.Optional[string] `json:"updated_by,omitempty"`
	UUID      string                 `json:"uuid"`
}

func (x ModelSecurityRuleInstanceResponse) MarshalJSON() ([]byte, error) {
	type alias ModelSecurityRuleInstanceResponse
	return internal.MarshalOptionalFields(alias(x))
}

// ModelSecurityRuleInstanceUpdateRequest represents Update rule instance.
type ModelSecurityRuleInstanceUpdateRequest struct {
	FieldValues       aisec.Optional[map[string]any] `json:"field_values,omitempty"`
	SecurityGroupUUID string                         `json:"security_group_uuid"`
	State             aisec.Optional[RuleState]      `json:"state,omitempty"`
}

func (x ModelSecurityRuleInstanceUpdateRequest) MarshalJSON() ([]byte, error) {
	type alias ModelSecurityRuleInstanceUpdateRequest
	return internal.MarshalOptionalFields(alias(x))
}

// ModelSecurityRuleListItem represents ModelSecurityRuleListItemSchema.
type ModelSecurityRuleListItem struct {
	CompatibleSources []SourceType        `json:"compatible_sources"`
	ConstantValues    map[string]any      `json:"constant_values"`
	DefaultState      RuleState           `json:"default_state"`
	DefaultValues     map[string]any      `json:"default_values"`
	Description       string              `json:"description"`
	EditableFields    []RuleEditableField `json:"editable_fields"`
	// Number of security groups that currently have this rule enabled. Null when reading a historical snapshot (via ?generation=N), since the count is a live value not captured in the snapshot.
	EnabledSecurityGroupCount aisec.Optional[int64] `json:"enabled_security_group_count,omitempty"`
	Name                      string                `json:"name"`
	Remediation               RuleRemediation       `json:"remediation"`
	RuleType                  RuleType              `json:"rule_type"`
	UUID                      string                `json:"uuid"`
}

func (x ModelSecurityRuleListItem) MarshalJSON() ([]byte, error) {
	type alias ModelSecurityRuleListItem
	return internal.MarshalOptionalFields(alias(x))
}

// ModelSecurityRuleResponse represents Response schema for model security rules - excludes internal fields like opa_path.
type ModelSecurityRuleResponse struct {
	CompatibleSources []SourceType        `json:"compatible_sources"`
	ConstantValues    map[string]any      `json:"constant_values"`
	DefaultState      RuleState           `json:"default_state"`
	DefaultValues     map[string]any      `json:"default_values"`
	Description       string              `json:"description"`
	EditableFields    []RuleEditableField `json:"editable_fields"`
	Name              string              `json:"name"`
	Remediation       RuleRemediation     `json:"remediation"`
	RuleType          RuleType            `json:"rule_type"`
	UUID              string              `json:"uuid"`
}

// ModelVersionList represents Schema for listing model versions..
type ModelVersionList struct {
	ModelVersions []ModelVersionResponse `json:"model_versions"`
	Pagination    Pagination             `json:"pagination"`
}

// ModelVersionResponse represents Schema for model version responses..
type ModelVersionResponse struct {
	CreatedAt       string                       `json:"created_at"`
	FileCount       aisec.Optional[int64]        `json:"file_count,omitempty"`
	Fingerprint     aisec.Optional[string]       `json:"fingerprint,omitempty"`
	HfCommitAuthors aisec.Optional[[]string]     `json:"hf_commit_authors,omitempty"`
	HfCommitSha     aisec.Optional[string]       `json:"hf_commit_sha,omitempty"`
	HfCommitTitle   aisec.Optional[string]       `json:"hf_commit_title,omitempty"`
	HfModelName     aisec.Optional[string]       `json:"hf_model_name,omitempty"`
	HfOrganization  aisec.Optional[string]       `json:"hf_organization,omitempty"`
	LastEvalOutcome aisec.Optional[EvalOutcome]  `json:"last_eval_outcome,omitempty"`
	LastEvalSummary aisec.Optional[EvalSummary]  `json:"last_eval_summary,omitempty"`
	LatestScanTime  aisec.Optional[string]       `json:"latest_scan_time,omitempty"`
	License         aisec.Optional[string]       `json:"license,omitempty"`
	ModelFormats    aisec.Optional[[]string]     `json:"model_formats,omitempty"`
	ModelUUID       string                       `json:"model_uuid"`
	Revision        string                       `json:"revision"`
	SourceTypes     aisec.Optional[[]SourceType] `json:"source_types,omitempty"`
	TSGID           string                       `json:"tsg_id"`
	UpdatedAt       string                       `json:"updated_at"`
	UUID            string                       `json:"uuid"`
}

func (x ModelVersionResponse) MarshalJSON() ([]byte, error) {
	type alias ModelVersionResponse
	return internal.MarshalOptionalFields(alias(x))
}

// Pagination represents PaginationSchema.
type Pagination struct {
	TotalItems aisec.Optional[int64] `json:"total_items,omitempty"`
}

func (x Pagination) MarshalJSON() ([]byte, error) {
	type alias Pagination
	return internal.MarshalOptionalFields(alias(x))
}

// PyPIAuthResponse represents Schema for PyPI authentication response..
type PyPIAuthResponse struct {
	// Token expiration timestamp in UTC
	ExpiresAt string `json:"expires_at"`
	// Authenticated Google Artifact Registry URL with embedded token
	URL string `json:"url"`
}

// RuleConfiguration represents Configuration for customizing a rule during security group creation..
type RuleConfiguration struct {
	// Dictionary for configuring policies custom settings to applicable policies. Allowed keys are approved_formats, approved_locations, approved_licenses, deny_orgs, and denied_org_models. Values should be a list of strings.
	FieldValues *map[string]any           `json:"field_values,omitempty"`
	State       aisec.Optional[RuleState] `json:"state,omitempty"`
}

func (x RuleConfiguration) MarshalJSON() ([]byte, error) {
	type alias RuleConfiguration
	return internal.MarshalOptionalFields(alias(x))
}

// RuleEditableField represents RuleEditableFieldSchema.
type RuleEditableField struct {
	AttributeName  string                                      `json:"attribute_name"`
	Description    aisec.Optional[string]                      `json:"description,omitempty"`
	DisplayName    string                                      `json:"display_name"`
	DisplayType    RuleEditableFieldType                       `json:"display_type"`
	DropdownValues aisec.Optional[[]RuleEditableFieldDropdown] `json:"dropdown_values,omitempty"`
	Type           string                                      `json:"type"`
}

func (x RuleEditableField) MarshalJSON() ([]byte, error) {
	type alias RuleEditableField
	return internal.MarshalOptionalFields(alias(x))
}

// RuleEditableFieldDropdown represents RuleEditableFieldDropdownSchema.
type RuleEditableFieldDropdown struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// RuleEditableFieldType represents Editable field types are used by rule structure for UI rendering.
type RuleEditableFieldType string

const (
	RuleEditableFieldTypeSelect RuleEditableFieldType = "SELECT"
	RuleEditableFieldTypeList   RuleEditableFieldType = "LIST"
)

// RuleEvaluationList represents RuleEvaluationListSchema.
type RuleEvaluationList struct {
	Evaluations []RuleEvaluationResponse `json:"evaluations"`
	Pagination  Pagination               `json:"pagination"`
}

// RuleEvaluationResponse represents RuleEvaluationResponseSchema.
type RuleEvaluationResponse struct {
	CreatedAt         string               `json:"created_at"`
	Result            RuleEvaluationResult `json:"result"`
	RuleDescription   string               `json:"rule_description"`
	RuleInstanceState RuleState            `json:"rule_instance_state"`
	RuleInstanceUUID  string               `json:"rule_instance_uuid"`
	RuleName          string               `json:"rule_name"`
	RuleOrigin        *RuleOrigin          `json:"rule_origin,omitempty"`
	ScanUUID          string               `json:"scan_uuid"`
	TSGID             string               `json:"tsg_id"`
	UpdatedAt         string               `json:"updated_at"`
	UUID              string               `json:"uuid"`
	ViolationCount    int64                `json:"violation_count"`
}

// RuleEvaluationResult represents Results of rule evaluation..
type RuleEvaluationResult string

const (
	RuleEvaluationResultPassed RuleEvaluationResult = "PASSED"
	RuleEvaluationResultFailed RuleEvaluationResult = "FAILED"
	RuleEvaluationResultError  RuleEvaluationResult = "ERROR"
)

// RuleFieldValueKey represents RuleFieldValueKey.
type RuleFieldValueKey string

const (
	RuleFieldValueKeyApprovedFormats   RuleFieldValueKey = "approved_formats"
	RuleFieldValueKeyApprovedLocations RuleFieldValueKey = "approved_locations"
	RuleFieldValueKeyApprovedLicenses  RuleFieldValueKey = "approved_licenses"
	RuleFieldValueKeyDenyOrgs          RuleFieldValueKey = "deny_orgs"
	RuleFieldValueKeyDeniedOrgModels   RuleFieldValueKey = "denied_org_models"
	RuleFieldValueKeyApprovedOrgModels RuleFieldValueKey = "approved_org_models"
)

// RuleOrigin represents Origin of a rule instance: PANW-managed template vs customer-authored custom rule..
type RuleOrigin string

const (
	RuleOriginPanwManaged RuleOrigin = "PANW_MANAGED"
	RuleOriginCustom      RuleOrigin = "CUSTOM"
)

// RuleRemediation represents Remediation steps for each rule.
type RuleRemediation struct {
	Description string   `json:"description"`
	Steps       []string `json:"steps"`
	URL         string   `json:"url"`
}

// RuleResultCondition represents RuleResultCondition.
type RuleResultCondition struct {
	Operator string `json:"operator"`
	RuleUUID string `json:"rule_uuid"`
	Type     string `json:"type"`
	Value    string `json:"value"`
}

// RuleState represents Rule evaluation states..
type RuleState string

const (
	RuleStateDisabled RuleState = "DISABLED"
	RuleStateAllowing RuleState = "ALLOWING"
	RuleStateBlocking RuleState = "BLOCKING"
)

// RuleType represents Rule types for different scanning approaches..
type RuleType string

const (
	RuleTypeMetadata RuleType = "METADATA"
	RuleTypeArtifact RuleType = "ARTIFACT"
)

// ScanBaseResponse represents ScanBaseResponseSchema.
type ScanBaseResponse struct {
	CreatedAt                string                      `json:"created_at"`
	CreatedBy                aisec.Optional[string]      `json:"created_by,omitempty"`
	EnabledRuleCountSnapshot aisec.Optional[int64]       `json:"enabled_rule_count_snapshot,omitempty"`
	ErrorCode                aisec.Optional[ErrorCodes]  `json:"error_code,omitempty"`
	ErrorMessage             aisec.Optional[string]      `json:"error_message,omitempty"`
	EvalOutcome              EvalOutcome                 `json:"eval_outcome"`
	EvalSummary              aisec.Optional[EvalSummary] `json:"eval_summary,omitempty"`
	Labels                   *[]Label                    `json:"labels,omitempty"`
	ModelFormats             aisec.Optional[[]string]    `json:"model_formats,omitempty"`
	ModelURI                 string                      `json:"model_uri"`
	ModelVersionUUID         aisec.Optional[string]      `json:"model_version_uuid,omitempty"`
	Owner                    string                      `json:"owner"`
	ScanOrigin               ScanOrigin                  `json:"scan_origin"`
	ScannerVersion           aisec.Optional[string]      `json:"scanner_version,omitempty"`
	SDKVersion               aisec.Optional[string]      `json:"sdk_version,omitempty"`
	SecurityGroupName        string                      `json:"security_group_name"`
	SecurityGroupUUID        string                      `json:"security_group_uuid"`
	SourceType               SourceType                  `json:"source_type"`
	TimeStarted              aisec.Optional[string]      `json:"time_started,omitempty"`
	TotalFilesScanned        aisec.Optional[int64]       `json:"total_files_scanned,omitempty"`
	TotalFilesSkipped        aisec.Optional[int64]       `json:"total_files_skipped,omitempty"`
	TSGID                    string                      `json:"tsg_id"`
	UpdatedAt                string                      `json:"updated_at"`
	UUID                     string                      `json:"uuid"`
}

func (x ScanBaseResponse) MarshalJSON() ([]byte, error) {
	type alias ScanBaseResponse
	return internal.MarshalOptionalFields(alias(x))
}

// ScanCreateRequest represents ScanCreateRequestSchema.
type ScanCreateRequest struct {
	AllowPatterns     aisec.Optional[[]string]    `json:"allow_patterns,omitempty"`
	IgnorePatterns    aisec.Optional[[]string]    `json:"ignore_patterns,omitempty"`
	Labels            aisec.Optional[[]Label]     `json:"labels,omitempty"`
	ModelAuthor       aisec.Optional[string]      `json:"model_author,omitempty"`
	ModelName         aisec.Optional[string]      `json:"model_name,omitempty"`
	ModelURI          string                      `json:"model_uri"`
	ModelVersion      aisec.Optional[string]      `json:"model_version,omitempty"`
	ScanDetails       aisec.Optional[ScanDetails] `json:"scan_details,omitempty"`
	ScanOrigin        aisec.Optional[ScanOrigin]  `json:"scan_origin,omitempty"`
	SecurityGroupUUID string                      `json:"security_group_uuid"`
}

func (x ScanCreateRequest) MarshalJSON() ([]byte, error) {
	type alias ScanCreateRequest
	return internal.MarshalOptionalFields(alias(x))
}

// ScanDetails represents ScanDetails.
type ScanDetails struct {
	ErrorCode         aisec.Optional[ErrorCodes] `json:"error_code,omitempty"`
	ErrorMessage      aisec.Optional[string]     `json:"error_message,omitempty"`
	Files             []FileScanData             `json:"files"`
	ModelFormats      []string                   `json:"model_formats"`
	ModelSizeBytes    int64                      `json:"model_size_bytes"`
	ScanDurationMS    int64                      `json:"scan_duration_ms"`
	ScannerVersion    string                     `json:"scanner_version"`
	TimeStarted       string                     `json:"time_started"`
	TotalFilesScanned int64                      `json:"total_files_scanned"`
	TotalFilesSkipped int64                      `json:"total_files_skipped"`
}

func (x ScanDetails) MarshalJSON() ([]byte, error) {
	type alias ScanDetails
	return internal.MarshalOptionalFields(alias(x))
}

// ScanList represents ScanListSchema.
type ScanList struct {
	CountCapped *bool              `json:"count_capped,omitempty"`
	Pagination  Pagination         `json:"pagination"`
	Scans       []ScanBaseResponse `json:"scans"`
}

// ScanOrigin represents ScanOrigin.
type ScanOrigin string

const (
	ScanOriginModelSecuritySDK      ScanOrigin = "MODEL_SECURITY_SDK"
	ScanOriginModelSecurityAPI      ScanOrigin = "MODEL_SECURITY_API"
	ScanOriginModelSecurityFrontend ScanOrigin = "MODEL_SECURITY_FRONTEND"
	ScanOriginHuggingFace           ScanOrigin = "HUGGING_FACE"
)

// SnapshotVersion represents One historical version of a GCS-backed snapshot, identified by its generation..
type SnapshotVersion struct {
	Generation int64  `json:"generation"`
	Timestamp  string `json:"timestamp"`
}

// SnapshotVersionListResponse represents A page of snapshot version history, newest first.
//
// Pagination is cursor-based over GCS object generations: pass “pagination.next_token“
// back as the “next_token“ query param to fetch the next page. “None“ when there are
// no more pages..
type SnapshotVersionListResponse struct {
	Pagination CursorPagination  `json:"pagination"`
	Versions   []SnapshotVersion `json:"versions"`
}

// SortByDateField represents SortByDateField.
type SortByDateField string

const (
	SortByDateFieldCreatedAt SortByDateField = "created_at"
	SortByDateFieldUpdatedAt SortByDateField = "updated_at"
)

// SortByFileField represents SortByFileField.
type SortByFileField string

const (
	SortByFileFieldPath SortByFileField = "path"
	SortByFileFieldType SortByFileField = "type"
)

// SortDirection represents SortDirection.
type SortDirection string

const (
	SortDirectionAsc  SortDirection = "asc"
	SortDirectionDesc SortDirection = "desc"
)

// SourceType represents SourceType.
type SourceType string

const (
	SourceTypeLocal       SourceType = "LOCAL"
	SourceTypeHuggingFace SourceType = "HUGGING_FACE"
	SourceTypeS3          SourceType = "S3"
	SourceTypeGcs         SourceType = "GCS"
	SourceTypeAzure       SourceType = "AZURE"
	SourceTypeArtifactory SourceType = "ARTIFACTORY"
	SourceTypeGitlab      SourceType = "GITLAB"
	SourceTypeAll         SourceType = "ALL"
)

// ThreatCategory represents Enum for threat categories with their descriptions.
// Should be in sync with modelscan-pai issue codes
// https://code.pan.run/airs/model-security/modelscan-pai/-/blob/1df3e4ca9f175398155ab1f249ed10211d222751/modelscan_pai/issues.py#L7.
type ThreatCategory string

const (
	ThreatCategoryPaitArv100        ThreatCategory = "PAIT-ARV-100"
	ThreatCategoryPaitGguf100       ThreatCategory = "PAIT-GGUF-100"
	ThreatCategoryPaitGguf101       ThreatCategory = "PAIT-GGUF-101"
	ThreatCategoryPaitKeras100      ThreatCategory = "PAIT-KERAS-100"
	ThreatCategoryPaitKeras101      ThreatCategory = "PAIT-KERAS-101"
	ThreatCategoryPaitKeras102      ThreatCategory = "PAIT-KERAS-102"
	ThreatCategoryPaitJoblib100     ThreatCategory = "PAIT-JOBLIB-100"
	ThreatCategoryPaitJoblib101     ThreatCategory = "PAIT-JOBLIB-101"
	ThreatCategoryPaitPkl100        ThreatCategory = "PAIT-PKL-100"
	ThreatCategoryPaitPkl101        ThreatCategory = "PAIT-PKL-101"
	ThreatCategoryPaitPytch100      ThreatCategory = "PAIT-PYTCH-100"
	ThreatCategoryPaitPytch101      ThreatCategory = "PAIT-PYTCH-101"
	ThreatCategoryPaitExdir100      ThreatCategory = "PAIT-EXDIR-100"
	ThreatCategoryPaitExdir101      ThreatCategory = "PAIT-EXDIR-101"
	ThreatCategoryPaitOnnx200       ThreatCategory = "PAIT-ONNX-200"
	ThreatCategoryPaitTf200         ThreatCategory = "PAIT-TF-200"
	ThreatCategoryPaitLmafl300      ThreatCategory = "PAIT-LMAFL-300"
	ThreatCategoryPaitLitert300     ThreatCategory = "PAIT-LITERT-300"
	ThreatCategoryPaitLitert301     ThreatCategory = "PAIT-LITERT-301"
	ThreatCategoryPaitLitert302     ThreatCategory = "PAIT-LITERT-302"
	ThreatCategoryPaitKeras300      ThreatCategory = "PAIT-KERAS-300"
	ThreatCategoryPaitKeras301      ThreatCategory = "PAIT-KERAS-301"
	ThreatCategoryPaitTchst300      ThreatCategory = "PAIT-TCHST-300"
	ThreatCategoryPaitTchst301      ThreatCategory = "PAIT-TCHST-301"
	ThreatCategoryPaitTf300         ThreatCategory = "PAIT-TF-300"
	ThreatCategoryPaitTf301         ThreatCategory = "PAIT-TF-301"
	ThreatCategoryPaitTf302         ThreatCategory = "PAIT-TF-302"
	ThreatCategoryPaitTmt300        ThreatCategory = "PAIT-TMT-300"
	ThreatCategoryPaitTmt301        ThreatCategory = "PAIT-TMT-301"
	ThreatCategoryUnapprovedFormats ThreatCategory = "UNAPPROVED_FORMATS"
)

// ValidationError represents ValidationError.
type ValidationError struct {
	Ctx   *map[string]any          `json:"ctx,omitempty"`
	Input *any                     `json:"input,omitempty"`
	Loc   []ValidationErrorLocItem `json:"loc"`
	Msg   string                   `json:"msg"`
	Type  string                   `json:"type"`
}

// ValidationErrorLocItem represents ValidationErrorLocItem.
type ValidationErrorLocItem json.RawMessage

func (x ValidationErrorLocItem) MarshalJSON() ([]byte, error) {
	return json.RawMessage(x).MarshalJSON()
}
func (x *ValidationErrorLocItem) UnmarshalJSON(data []byte) error {
	if !json.Valid(data) {
		return fmt.Errorf("invalid ValidationErrorLocItem JSON")
	}
	candidate := ValidationErrorLocItem(data)
	valid := false
	if _, err := candidate.AsString(); err == nil {
		valid = true
	}
	if _, err := candidate.AsInt64(); err == nil {
		valid = true
	}
	if !valid {
		return fmt.Errorf("no matching ValidationErrorLocItem alternative")
	}
	*x = append((*x)[:0], data...)
	return nil
}

// AsString decodes this union as string; tagged variants verify their tag.
func (x ValidationErrorLocItem) AsString() (*string, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null ValidationErrorLocItem alternative")
	}
	var value string
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	return &value, nil
}

// NewValidationErrorLocItemFromString encodes the typed union alternative.
func NewValidationErrorLocItemFromString(value string) (ValidationErrorLocItem, error) {
	b, err := json.Marshal(value)
	return ValidationErrorLocItem(b), err
}

// AsInt64 decodes this union as int64; tagged variants verify their tag.
func (x ValidationErrorLocItem) AsInt64() (*int64, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null ValidationErrorLocItem alternative")
	}
	var value int64
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	return &value, nil
}

// NewValidationErrorLocItemFromInt64 encodes the typed union alternative.
func NewValidationErrorLocItemFromInt64(value int64) (ValidationErrorLocItem, error) {
	b, err := json.Marshal(value)
	return ValidationErrorLocItem(b), err
}

// ViolationList represents Schema for violation list responses..
type ViolationList struct {
	Pagination Pagination          `json:"pagination"`
	Violations []ViolationResponse `json:"violations"`
}

// ViolationRemediation represents Remediation returned on violations — steps and reference URL only..
type ViolationRemediation struct {
	Steps []string               `json:"steps"`
	URL   aisec.Optional[string] `json:"url,omitempty"`
}

func (x ViolationRemediation) MarshalJSON() ([]byte, error) {
	type alias ViolationRemediation
	return internal.MarshalOptionalFields(alias(x))
}

// ViolationResponse represents Schema for violation responses with enhanced rule details..
type ViolationResponse struct {
	CreatedAt         string                               `json:"created_at"`
	Description       string                               `json:"description"`
	File              aisec.Optional[string]               `json:"file,omitempty"`
	Hash              aisec.Optional[string]               `json:"hash,omitempty"`
	InsightsURL       aisec.Optional[string]               `json:"insights_url,omitempty"`
	Module            aisec.Optional[string]               `json:"module,omitempty"`
	Operator          aisec.Optional[string]               `json:"operator,omitempty"`
	Remediation       aisec.Optional[ViolationRemediation] `json:"remediation,omitempty"`
	RuleDescription   string                               `json:"rule_description"`
	RuleInstanceState RuleState                            `json:"rule_instance_state"`
	RuleInstanceUUID  string                               `json:"rule_instance_uuid"`
	RuleName          string                               `json:"rule_name"`
	RuleOrigin        *RuleOrigin                          `json:"rule_origin,omitempty"`
	Threat            aisec.Optional[ThreatCategory]       `json:"threat,omitempty"`
	ThreatDescription aisec.Optional[string]               `json:"threat_description,omitempty"`
	ThreatKBURL       aisec.Optional[string]               `json:"threat_kb_url,omitempty"`
	TSGID             string                               `json:"tsg_id"`
	UpdatedAt         string                               `json:"updated_at"`
	UUID              string                               `json:"uuid"`
}

func (x ViolationResponse) MarshalJSON() ([]byte, error) {
	type alias ViolationResponse
	return internal.MarshalOptionalFields(alias(x))
}
