// Code generated by scripts/schema_models.py from specs/contracts; DO NOT EDIT.

package schema

import (
	"bytes"
	"fmt"

	"encoding/json"
	"github.com/cdot65/prisma-airs-go/aisec"
	"github.com/cdot65/prisma-airs-go/aisec/internal"
)

// AgentGuardAttackChainList represents AgentGuardAttackChainListSchema.
type AgentGuardAttackChainList struct {
	AttackChains []AgentGuardAttackChainSummaryResponse `json:"attack_chains"`
	Pagination   Pagination                             `json:"pagination"`
}

// AgentGuardAttackChainResponse represents AgentGuardAttackChainResponseSchema.
type AgentGuardAttackChainResponse struct {
	CreatedAt          string                      `json:"created_at"`
	Description        string                      `json:"description"`
	Impact             string                      `json:"impact"`
	RemediationSummary aisec.Optional[string]      `json:"remediation_summary,omitempty"`
	ScanUUID           string                      `json:"scan_uuid"`
	Steps              []AgentGuardAttackChainStep `json:"steps"`
	Title              string                      `json:"title"`
	TSGID              string                      `json:"tsg_id"`
	UpdatedAt          string                      `json:"updated_at"`
	UUID               string                      `json:"uuid"`
	VulnerabilityCount int64                       `json:"vulnerability_count"`
	VulnerabilityUuids []string                    `json:"vulnerability_uuids"`
}

func (x AgentGuardAttackChainResponse) MarshalJSON() ([]byte, error) {
	type alias AgentGuardAttackChainResponse
	return internal.MarshalOptionalFields(alias(x))
}

// AgentGuardAttackChainStep represents AgentGuardAttackChainStepSchema.
type AgentGuardAttackChainStep struct {
	Description        string                 `json:"description"`
	ImpactDescription  aisec.Optional[string] `json:"impact_description,omitempty"`
	NodeID             string                 `json:"node_id"`
	NodeName           string                 `json:"node_name"`
	NodeType           NodeType               `json:"node_type"`
	StepNumber         int64                  `json:"step_number"`
	StepType           StepType               `json:"step_type"`
	VulnerabilityTitle aisec.Optional[string] `json:"vulnerability_title,omitempty"`
	VulnerabilityUUID  aisec.Optional[string] `json:"vulnerability_uuid,omitempty"`
}

func (x AgentGuardAttackChainStep) MarshalJSON() ([]byte, error) {
	type alias AgentGuardAttackChainStep
	return internal.MarshalOptionalFields(alias(x))
}

// AgentGuardAttackChainSummaryResponse represents AgentGuardAttackChainSummaryResponseSchema.
type AgentGuardAttackChainSummaryResponse struct {
	CreatedAt          string                 `json:"created_at"`
	Description        string                 `json:"description"`
	Impact             string                 `json:"impact"`
	RemediationSummary aisec.Optional[string] `json:"remediation_summary,omitempty"`
	ScanUUID           string                 `json:"scan_uuid"`
	Title              string                 `json:"title"`
	TSGID              string                 `json:"tsg_id"`
	UpdatedAt          string                 `json:"updated_at"`
	UUID               string                 `json:"uuid"`
	VulnerabilityCount int64                  `json:"vulnerability_count"`
	VulnerabilityUuids []string               `json:"vulnerability_uuids"`
}

func (x AgentGuardAttackChainSummaryResponse) MarshalJSON() ([]byte, error) {
	type alias AgentGuardAttackChainSummaryResponse
	return internal.MarshalOptionalFields(alias(x))
}

// AgentGuardBatchSummary represents Counts rolled up from a batch parent's child scans..
type AgentGuardBatchSummary struct {
	Allowed   int64 `json:"allowed"`
	Blocked   int64 `json:"blocked"`
	Completed int64 `json:"completed"`
	Failed    int64 `json:"failed"`
	Total     int64 `json:"total"`
}

// AgentGuardEvalDetails represents AgentGuardEvalDetailsSchema.
type AgentGuardEvalDetails struct {
	RuleOutcomes         *[]AgentGuardRuleOutcome `json:"rule_outcomes,omitempty"`
	SkillOverrideApplied *bool                    `json:"skill_override_applied,omitempty"`
	UnknownFindings      *[]string                `json:"unknown_findings,omitempty"`
}

// AgentGuardEvalSummary represents AgentGuardEvalSummarySchema.
type AgentGuardEvalSummary struct {
	Allowed    int64 `json:"allowed"`
	Blocked    int64 `json:"blocked"`
	TotalRules int64 `json:"total_rules"`
}

// AgentGuardRuleOutcome represents AgentGuardRuleOutcomeSchema.
type AgentGuardRuleOutcome struct {
	Description        string   `json:"description"`
	Outcome            string   `json:"outcome"`
	Remediation        string   `json:"remediation"`
	RuleInstanceUUID   string   `json:"rule_instance_uuid"`
	RuleName           string   `json:"rule_name"`
	State              string   `json:"state"`
	VulnerabilityCount int64    `json:"vulnerability_count"`
	VulnerabilityTypes []string `json:"vulnerability_types"`
}

// AgentGuardScanList represents AgentGuardScanListSchema.
type AgentGuardScanList struct {
	Pagination Pagination               `json:"pagination"`
	Scans      []AgentGuardScanResponse `json:"scans"`
}

// AgentGuardScanResponse represents AgentGuardScanResponseSchema.
type AgentGuardScanResponse struct {
	ArtifactType    aisec.Optional[string]                 `json:"artifact_type,omitempty"`
	BatchSummary    aisec.Optional[AgentGuardBatchSummary] `json:"batch_summary,omitempty"`
	ChildScanUuids  *[]string                              `json:"child_scan_uuids,omitempty"`
	CreatedAt       string                                 `json:"created_at"`
	DeviceMetadata  aisec.Optional[DeviceMetadata]         `json:"device_metadata,omitempty"`
	DurationSeconds aisec.Optional[int64]                  `json:"duration_seconds,omitempty"`
	ErrorMessage    aisec.Optional[string]                 `json:"error_message,omitempty"`
	EvalDetails     aisec.Optional[AgentGuardEvalDetails]  `json:"eval_details,omitempty"`
	EvalOutcome     aisec.Optional[EvalOutcome]            `json:"eval_outcome,omitempty"`
	EvalSummary     aisec.Optional[AgentGuardEvalSummary]  `json:"eval_summary,omitempty"`
	Fingerprint     aisec.Optional[string]                 `json:"fingerprint,omitempty"`
	GitURL          aisec.Optional[string]                 `json:"git_url,omitempty"`
	IsBatch         *bool                                  `json:"is_batch,omitempty"`
	Name            string                                 `json:"name"`
	ParentUUID      aisec.Optional[string]                 `json:"parent_uuid,omitempty"`
	ScannerVersion  aisec.Optional[string]                 `json:"scanner_version,omitempty"`
	Status          AgentGuardScanStatus                   `json:"status"`
	Summary         aisec.Optional[AgentGuardScanSummary]  `json:"summary,omitempty"`
	TSGID           string                                 `json:"tsg_id"`
	UpdatedAt       string                                 `json:"updated_at"`
	UUID            string                                 `json:"uuid"`
}

func (x AgentGuardScanResponse) MarshalJSON() ([]byte, error) {
	type alias AgentGuardScanResponse
	return internal.MarshalOptionalFields(alias(x))
}

// AgentGuardScanStatsResponse represents Summary cards for the skill scans page.
//
// The three numbers deliberately use different grains: the first counts distinct
// skills, the other two count per scan. A skill scanned thirty times with four
// findings each is 1 unique skill and 120 findings..
type AgentGuardScanStatsResponse struct {
	// The most frequently found vulnerability type in the window, or null when nothing was found.
	TopVulnerability aisec.Optional[AgentGuardTopVulnerability] `json:"top_vulnerability,omitempty"`
	// Findings across all scans in the window, counted per scan rather than per distinct skill, so a skill scanned repeatedly contributes its findings each time.
	TotalVulnerabilitiesFound StatWithChange `json:"total_vulnerabilities_found"`
	// Distinct skills scanned in the window, counted by fingerprint, with the change against the preceding window of equal length. A skill scanned many times counts once. Windows are whole UTC days.
	UniqueSkillsScanned StatWithChange `json:"unique_skills_scanned"`
}

func (x AgentGuardScanStatsResponse) MarshalJSON() ([]byte, error) {
	type alias AgentGuardScanStatsResponse
	return internal.MarshalOptionalFields(alias(x))
}

// AgentGuardScanStatus represents Status of an AgentGuard scan..
type AgentGuardScanStatus string

const (
	AgentGuardScanStatusUploading   AgentGuardScanStatus = "UPLOADING"
	AgentGuardScanStatusClassifying AgentGuardScanStatus = "CLASSIFYING"
	AgentGuardScanStatusAnalyzing   AgentGuardScanStatus = "ANALYZING"
	AgentGuardScanStatusCompleted   AgentGuardScanStatus = "COMPLETED"
	AgentGuardScanStatusFailed      AgentGuardScanStatus = "FAILED"
	AgentGuardScanStatusError       AgentGuardScanStatus = "ERROR"
)

// AgentGuardScanSummary represents AgentGuardScanSummarySchema.
type AgentGuardScanSummary struct {
	AttackChainCount   int64 `json:"attack_chain_count"`
	VulnerabilityCount int64 `json:"vulnerability_count"`
}

// AgentGuardSkillStatsResponse represents Summary cards for the Skill Scanning Rules tab..
type AgentGuardSkillStatsResponse struct {
	// Catalog rules ranked by failures in the window, highest first, filtered to rules that are still enabled, capped at 10. Null when the rule configuration could not be read, since neither filtering nor naming is possible; an empty list means the tenant genuinely tripped no enabled rules. Counts here need not sum to total_rule_violations: failures attributed to rules that have since been disabled stay in the total but drop out of this list, as do any beyond the tenth.
	MostViolatedRules aisec.Optional[[]MostBlockedRule] `json:"most_violated_rules,omitempty"`
	// Distinct skill rules currently switched on for the tenant, counting both blocking and alert-only rules. Null when the rule configuration could not be read, which is distinct from 0 -- 0 means the tenant genuinely has no rules enabled.
	TotalEnabledRules *int64 `json:"total_enabled_rules"`
	// Failed rule evaluations in the requested window, with the change against the preceding window of equal length. Skills the tenant has trusted via a skill override are excluded.
	TotalRuleViolations StatWithChange `json:"total_rule_violations"`
}

func (x AgentGuardSkillStatsResponse) MarshalJSON() ([]byte, error) {
	type alias AgentGuardSkillStatsResponse
	return internal.MarshalOptionalFields(alias(x))
}

// AgentGuardTopVulnerability represents The vulnerability type found most often in the window..
type AgentGuardTopVulnerability struct {
	// Findings of this type across all scans in the window
	FindingCount int64 `json:"finding_count"`
	// Vulnerability type, e.g. CODE_EXECUTION
	VulnerabilityType string `json:"vulnerability_type"`
}

// AgentGuardUploadCompleteRequest represents AgentGuardUploadCompleteRequestSchema.
type AgentGuardUploadCompleteRequest struct {
	// Base64-encoded CRC32C of the uploaded archive (4 bytes, big-endian) - the canonical GCS representation, e.g. 'yZRlqg=='.
	ChecksumCrc32c aisec.Optional[string]         `json:"checksum_crc32c,omitempty"`
	DeviceMetadata aisec.Optional[DeviceMetadata] `json:"device_metadata,omitempty"`
	GitURL         aisec.Optional[string]         `json:"git_url,omitempty"`
	Name           string                         `json:"name"`
}

func (x AgentGuardUploadCompleteRequest) MarshalJSON() ([]byte, error) {
	type alias AgentGuardUploadCompleteRequest
	return internal.MarshalOptionalFields(alias(x))
}

// AgentGuardUploadCompleteResponse represents AgentGuardUploadCompleteResponseSchema.
type AgentGuardUploadCompleteResponse struct {
	ArtifactType    aisec.Optional[string]                 `json:"artifact_type,omitempty"`
	BatchSummary    aisec.Optional[AgentGuardBatchSummary] `json:"batch_summary,omitempty"`
	ChildScanUuids  *[]string                              `json:"child_scan_uuids,omitempty"`
	CreatedAt       string                                 `json:"created_at"`
	DeviceMetadata  aisec.Optional[DeviceMetadata]         `json:"device_metadata,omitempty"`
	DurationSeconds aisec.Optional[int64]                  `json:"duration_seconds,omitempty"`
	ErrorMessage    aisec.Optional[string]                 `json:"error_message,omitempty"`
	EvalDetails     aisec.Optional[AgentGuardEvalDetails]  `json:"eval_details,omitempty"`
	EvalOutcome     aisec.Optional[EvalOutcome]            `json:"eval_outcome,omitempty"`
	EvalSummary     aisec.Optional[AgentGuardEvalSummary]  `json:"eval_summary,omitempty"`
	Fingerprint     aisec.Optional[string]                 `json:"fingerprint,omitempty"`
	GitURL          aisec.Optional[string]                 `json:"git_url,omitempty"`
	IsBatch         *bool                                  `json:"is_batch,omitempty"`
	Name            string                                 `json:"name"`
	ParentUUID      aisec.Optional[string]                 `json:"parent_uuid,omitempty"`
	ScannerVersion  aisec.Optional[string]                 `json:"scanner_version,omitempty"`
	Status          AgentGuardScanStatus                   `json:"status"`
	Summary         aisec.Optional[AgentGuardScanSummary]  `json:"summary,omitempty"`
	TSGID           string                                 `json:"tsg_id"`
	UpdatedAt       string                                 `json:"updated_at"`
	UUID            string                                 `json:"uuid"`
}

func (x AgentGuardUploadCompleteResponse) MarshalJSON() ([]byte, error) {
	type alias AgentGuardUploadCompleteResponse
	return internal.MarshalOptionalFields(alias(x))
}

// AgentGuardUploadURLResponse represents AgentGuardUploadUrlResponseSchema.
type AgentGuardUploadURLResponse struct {
	ScanUUID        string `json:"scan_uuid"`
	UploadExpiresAt string `json:"upload_expires_at"`
	UploadURL       string `json:"upload_url"`
}

// AgentGuardVulnerabilityList represents AgentGuardVulnerabilityListSchema.
type AgentGuardVulnerabilityList struct {
	Pagination      Pagination                        `json:"pagination"`
	Vulnerabilities []AgentGuardVulnerabilityResponse `json:"vulnerabilities"`
}

// AgentGuardVulnerabilityResponse represents AgentGuardVulnerabilityResponseSchema.
type AgentGuardVulnerabilityResponse struct {
	AttackChainCount       int64                    `json:"attack_chain_count"`
	AttackChainUuids       []string                 `json:"attack_chain_uuids"`
	CreatedAt              string                   `json:"created_at"`
	Description            string                   `json:"description"`
	FilePath               aisec.Optional[string]   `json:"file_path,omitempty"`
	NodeID                 aisec.Optional[string]   `json:"node_id,omitempty"`
	NodeName               aisec.Optional[string]   `json:"node_name,omitempty"`
	NodeType               aisec.Optional[NodeType] `json:"node_type,omitempty"`
	OriginalCode           aisec.Optional[string]   `json:"original_code,omitempty"`
	RemediationDescription aisec.Optional[string]   `json:"remediation_description,omitempty"`
	ScanUUID               string                   `json:"scan_uuid"`
	SuggestedCode          aisec.Optional[string]   `json:"suggested_code,omitempty"`
	Title                  string                   `json:"title"`
	TSGID                  string                   `json:"tsg_id"`
	TypeDescription        *string                  `json:"type_description"`
	UpdatedAt              string                   `json:"updated_at"`
	UUID                   string                   `json:"uuid"`
	VulnerabilityType      VulnerabilityType        `json:"vulnerability_type"`
}

func (x AgentGuardVulnerabilityResponse) MarshalJSON() ([]byte, error) {
	type alias AgentGuardVulnerabilityResponse
	return internal.MarshalOptionalFields(alias(x))
}

// ArtifactType represents Types of artifacts in AgentGuard..
type ArtifactType string

const (
	ArtifactTypeAgent ArtifactType = "AGENT"
	ArtifactTypeSkill ArtifactType = "SKILL"
)

// DeploymentProfile represents Schema for deployment profile in instance response.
type DeploymentProfile struct {
	// Activation timestamp in ISO format
	ActivatedAt aisec.Optional[string] `json:"activated_at,omitempty"`
	// Authorization code
	AuthCode string `json:"auth_code"`
	// Creator email or empty string
	CreatedBy aisec.Optional[string] `json:"created_by,omitempty"`
	// Deployment profile name
	DPName aisec.Optional[string] `json:"dp_name,omitempty"`
	// License expiration in ISO format
	LicenseExpiration aisec.Optional[string] `json:"license_expiration,omitempty"`
	// Device serial number
	SerialNumber aisec.Optional[string] `json:"serial_number,omitempty"`
	// Human-readable status
	Status string `json:"status"`
}

func (x DeploymentProfile) MarshalJSON() ([]byte, error) {
	type alias DeploymentProfile
	return internal.MarshalOptionalFields(alias(x))
}

// DeviceMetadata represents DeviceMetadataSchema.
type DeviceMetadata struct {
	DeviceID string `json:"device_id"`
	Os       string `json:"os"`
	Tool     string `json:"tool"`
	Username string `json:"username"`
}

// EvalOutcome represents EvalOutcome.
type EvalOutcome string

const (
	EvalOutcomePending EvalOutcome = "PENDING"
	EvalOutcomeAllowed EvalOutcome = "ALLOWED"
	EvalOutcomeBlocked EvalOutcome = "BLOCKED"
	EvalOutcomeError   EvalOutcome = "ERROR"
)

// HTTPValidationError represents HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// Instance represents Schema for instance details with deployment profiles.
type Instance struct {
	// Creator email or empty string
	CreatedBy *string `json:"created_by,omitempty"`
	// List of deployment profiles
	DeploymentProfiles *[]DeploymentProfile `json:"deployment_profiles,omitempty"`
	// CSP ID
	SupportAccountID string `json:"support_account_id"`
	// Support account name or empty
	SupportAccountName *string `json:"support_account_name,omitempty"`
	// Tenant ID
	TenantID string `json:"tenant_id"`
	// TSG ID
	TSGID string `json:"tsg_id"`
}

// InstanceCreateModel represents Schema for creating a new instance.
type InstanceCreateModel struct {
	AuthCode           aisec.Optional[string]           `json:"auth_code,omitempty"`
	CreatedBy          string                           `json:"created_by"`
	CspTenantID        aisec.Optional[string]           `json:"csp_tenant_id,omitempty"`
	Entitlements       aisec.Optional[[]any]            `json:"entitlements,omitempty"`
	Extra              *map[string]any                  `json:"extra,omitempty"`
	IamControlled      aisec.Optional[bool]             `json:"iam_controlled,omitempty"`
	LicenseName        aisec.Optional[string]           `json:"license_name,omitempty"`
	PlatformRegion     aisec.Optional[string]           `json:"platform_region,omitempty"`
	Region             aisec.Optional[string]           `json:"region,omitempty"`
	SerialNumber       aisec.Optional[string]           `json:"serial_number,omitempty"`
	SupportAccountID   string                           `json:"support_account_id"`
	SupportAccountName aisec.Optional[string]           `json:"support_account_name,omitempty"`
	TenantID           string                           `json:"tenant_id"`
	TenantInstanceName aisec.Optional[string]           `json:"tenant_instance_name,omitempty"`
	TSGID              string                           `json:"tsg_id"`
	TSGInstances       aisec.Optional[[]map[string]any] `json:"tsg_instances,omitempty"`
	AdditionalFields   map[string]json.RawMessage       `json:"-"`
}

func (x InstanceCreateModel) MarshalJSON() ([]byte, error) {
	type alias InstanceCreateModel
	return marshalFields(alias(x), x.AdditionalFields, []string{"auth_code", "created_by", "csp_tenant_id", "entitlements", "extra", "iam_controlled", "license_name", "platform_region", "region", "serial_number", "support_account_id", "support_account_name", "tenant_id", "tenant_instance_name", "tsg_id", "tsg_instances"})
}
func (x *InstanceCreateModel) UnmarshalJSON(data []byte) error {
	type alias InstanceCreateModel
	var candidate alias
	extra, err := unmarshalFields(data, &candidate, []string{"auth_code", "created_by", "csp_tenant_id", "entitlements", "extra", "iam_controlled", "license_name", "platform_region", "region", "serial_number", "support_account_id", "support_account_name", "tenant_id", "tenant_instance_name", "tsg_id", "tsg_instances"})
	if err != nil {
		return err
	}
	candidate.AdditionalFields = extra
	*x = InstanceCreateModel(candidate)
	return nil
}

// InstanceResponseModel represents InstanceResponseModelSchema.
type InstanceResponseModel struct {
	IsSuccess bool                   `json:"is_success"`
	TenantID  string                 `json:"tenant_id"`
	TSGID     aisec.Optional[string] `json:"tsg_id,omitempty"`
}

func (x InstanceResponseModel) MarshalJSON() ([]byte, error) {
	type alias InstanceResponseModel
	return internal.MarshalOptionalFields(alias(x))
}

// ListSkillOverridesResponse represents ListSkillOverridesResponseSchema.
type ListSkillOverridesResponse struct {
	Pagination     Pagination              `json:"pagination"`
	SkillOverrides []SkillOverrideResponse `json:"skill_overrides"`
}

// ListSkillSecurityRuleInstancesResponse represents ListSkillSecurityRuleInstancesResponseSchema.
type ListSkillSecurityRuleInstancesResponse struct {
	Pagination    Pagination                          `json:"pagination"`
	RuleInstances []SkillSecurityRuleInstanceResponse `json:"rule_instances"`
}

// ListSkillSecurityRulesResponse represents ListSkillSecurityRulesResponseSchema.
type ListSkillSecurityRulesResponse struct {
	Pagination Pagination                  `json:"pagination"`
	Rules      []SkillSecurityRuleResponse `json:"rules"`
}

// MostBlockedRule represents Information about the most frequently blocking rule template..
type MostBlockedRule struct {
	// Name of the rule template
	RuleName string `json:"rule_name"`
	// UUID of the rule template (aggregated across all security groups)
	RuleUUID string `json:"rule_uuid"`
	// Total number of violations caused by this rule template across ALL security groups
	ViolationCount int64 `json:"violation_count"`
}

// NodeType represents Types of nodes in an agent architecture graph..
type NodeType string

const (
	NodeTypeAgent      NodeType = "AGENT"
	NodeTypeTool       NodeType = "TOOL"
	NodeTypeDataSource NodeType = "DATA_SOURCE"
	NodeTypeDataAsset  NodeType = "DATA_ASSET"
	NodeTypeMemory     NodeType = "MEMORY"
)

// OverrideDecision represents OverrideDecision.
type OverrideDecision string

const (
	OverrideDecisionAllow OverrideDecision = "ALLOW"
)

// Pagination represents PaginationSchema.
type Pagination struct {
	TotalItems aisec.Optional[int64] `json:"total_items,omitempty"`
}

func (x Pagination) MarshalJSON() ([]byte, error) {
	type alias Pagination
	return internal.MarshalOptionalFields(alias(x))
}

// RuleState represents Rule evaluation states..
type RuleState string

const (
	RuleStateDisabled RuleState = "DISABLED"
	RuleStateAllowing RuleState = "ALLOWING"
	RuleStateBlocking RuleState = "BLOCKING"
)

// SkillOverrideCreateRequest represents SkillOverrideCreateRequestSchema.
type SkillOverrideCreateRequest struct {
	Decision         OverrideDecision       `json:"decision"`
	Fingerprint      string                 `json:"fingerprint"`
	OriginalScanUUID aisec.Optional[string] `json:"original_scan_uuid,omitempty"`
	Reason           aisec.Optional[string] `json:"reason,omitempty"`
	SkillName        string                 `json:"skill_name"`
	TrustedBy        string                 `json:"trusted_by"`
}

func (x SkillOverrideCreateRequest) MarshalJSON() ([]byte, error) {
	type alias SkillOverrideCreateRequest
	return internal.MarshalOptionalFields(alias(x))
}

// SkillOverrideResponse represents SkillOverrideResponseSchema.
type SkillOverrideResponse struct {
	CreatedAt        string           `json:"created_at"`
	CreatedBy        string           `json:"created_by"`
	Decision         OverrideDecision `json:"decision"`
	Fingerprint      string           `json:"fingerprint"`
	OriginalScanUUID *string          `json:"original_scan_uuid"`
	Reason           *string          `json:"reason"`
	SkillName        string           `json:"skill_name"`
	TrustedBy        *string          `json:"trusted_by"`
	TSGID            string           `json:"tsg_id"`
	UpdatedAt        string           `json:"updated_at"`
	UUID             string           `json:"uuid"`
}

// SkillSecurityRuleConfiguration represents Desired state for a single rule in a rule-instances update request..
type SkillSecurityRuleConfiguration struct {
	State RuleState `json:"state"`
}

// SkillSecurityRuleInstanceResponse represents SkillSecurityRuleInstanceResponseSchema.
type SkillSecurityRuleInstanceResponse struct {
	CreatedAt         string                    `json:"created_at"`
	Rule              SkillSecurityRuleResponse `json:"rule"`
	RuleUUID          string                    `json:"rule_uuid"`
	SecurityGroupUUID string                    `json:"security_group_uuid"`
	State             RuleState                 `json:"state"`
	TSGID             string                    `json:"tsg_id"`
	UpdatedAt         string                    `json:"updated_at"`
	UUID              string                    `json:"uuid"`
}

// SkillSecurityRuleInstancesUpdateRequest represents Atomically update rule-instance state for one or more rules, keyed by
// rule_uuid, in the tenant's singleton skill-security-group..
type SkillSecurityRuleInstancesUpdateRequest struct {
	// Map of rule_uuid -> desired state.
	RuleConfigurations map[string]SkillSecurityRuleConfiguration `json:"rule_configurations"`
}

// SkillSecurityRuleResponse represents SkillSecurityRuleResponseSchema.
type SkillSecurityRuleResponse struct {
	DefaultState       RuleState `json:"default_state"`
	Description        string    `json:"description"`
	Name               string    `json:"name"`
	Remediation        string    `json:"remediation"`
	UUID               string    `json:"uuid"`
	VulnerabilityTypes []string  `json:"vulnerability_types"`
}

// SortDirection represents SortDirection.
type SortDirection string

const (
	SortDirectionAsc  SortDirection = "asc"
	SortDirectionDesc SortDirection = "desc"
)

// StatWithChange represents Statistic value with percentage change from previous period..
type StatWithChange struct {
	// Current count for this statistic
	Count int64 `json:"count"`
	// Percentage change from previous equivalent time period. None if no previous data exists.
	PercentChange *float64 `json:"percent_change"`
}

// StepType represents Types of steps in an attack path..
type StepType string

const (
	StepTypeVulnerability StepType = "VULNERABILITY"
	StepTypeNormal        StepType = "NORMAL"
	StepTypeImpact        StepType = "IMPACT"
)

// TimePeriod represents Time period options for statistics queries.
//
// Each period has an associated stats_step (the bucket granularity to query)
// and time_delta (the lookback duration from reference time)..
type TimePeriod string

const (
	TimePeriodValue1Hour   TimePeriod = "1_HOUR"
	TimePeriodValue3Hours  TimePeriod = "3_HOURS"
	TimePeriodValue24Hours TimePeriod = "24_HOURS"
	TimePeriodValue7Days   TimePeriod = "7_DAYS"
	TimePeriodValue30Days  TimePeriod = "30_DAYS"
	TimePeriodAllTime      TimePeriod = "ALL_TIME"
)

// ValidationError represents ValidationError.
type ValidationError struct {
	Ctx   *map[string]any          `json:"ctx,omitempty"`
	Input *any                     `json:"input,omitempty"`
	Loc   []ValidationErrorLocItem `json:"loc"`
	Msg   string                   `json:"msg"`
	Type  string                   `json:"type"`
}

// ValidationErrorLocItem represents ValidationErrorLocItem.
type ValidationErrorLocItem json.RawMessage

func (x ValidationErrorLocItem) MarshalJSON() ([]byte, error) {
	return json.RawMessage(x).MarshalJSON()
}
func (x *ValidationErrorLocItem) UnmarshalJSON(data []byte) error {
	if !json.Valid(data) {
		return fmt.Errorf("invalid ValidationErrorLocItem JSON")
	}
	candidate := ValidationErrorLocItem(data)
	valid := false
	if _, err := candidate.AsString(); err == nil {
		valid = true
	}
	if _, err := candidate.AsInt64(); err == nil {
		valid = true
	}
	if !valid {
		return fmt.Errorf("no matching ValidationErrorLocItem alternative")
	}
	*x = append((*x)[:0], data...)
	return nil
}

// AsString decodes this union as string; tagged variants verify their tag.
func (x ValidationErrorLocItem) AsString() (*string, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null ValidationErrorLocItem alternative")
	}
	var value string
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	return &value, nil
}

// NewValidationErrorLocItemFromString encodes the typed union alternative.
func NewValidationErrorLocItemFromString(value string) (ValidationErrorLocItem, error) {
	b, err := json.Marshal(value)
	return ValidationErrorLocItem(b), err
}

// AsInt64 decodes this union as int64; tagged variants verify their tag.
func (x ValidationErrorLocItem) AsInt64() (*int64, error) {
	if bytes.Equal(bytes.TrimSpace(x), []byte("null")) {
		return nil, fmt.Errorf("null ValidationErrorLocItem alternative")
	}
	var value int64
	if err := json.Unmarshal(x, &value); err != nil {
		return nil, err
	}
	return &value, nil
}

// NewValidationErrorLocItemFromInt64 encodes the typed union alternative.
func NewValidationErrorLocItemFromInt64(value int64) (ValidationErrorLocItem, error) {
	b, err := json.Marshal(value)
	return ValidationErrorLocItem(b), err
}

// VulnerabilityType represents Types of vulnerabilities detected in agent scans..
type VulnerabilityType string

const (
	VulnerabilityTypePromptInjection       VulnerabilityType = "PROMPT_INJECTION"
	VulnerabilityTypeCodeExecution         VulnerabilityType = "CODE_EXECUTION"
	VulnerabilityTypeNetworkExposure       VulnerabilityType = "NETWORK_EXPOSURE"
	VulnerabilityTypeDataExfiltration      VulnerabilityType = "DATA_EXFILTRATION"
	VulnerabilityTypePrivilegeEscalation   VulnerabilityType = "PRIVILEGE_ESCALATION"
	VulnerabilityTypeAuthenticationBypass  VulnerabilityType = "AUTHENTICATION_BYPASS"
	VulnerabilityTypeXss                   VulnerabilityType = "XSS"
	VulnerabilityTypeSsrf                  VulnerabilityType = "SSRF"
	VulnerabilityTypeSqlInjection          VulnerabilityType = "SQL_INJECTION"
	VulnerabilityTypePathTraversal         VulnerabilityType = "PATH_TRAVERSAL"
	VulnerabilityTypeInformationDisclosure VulnerabilityType = "INFORMATION_DISCLOSURE"
	VulnerabilityTypeDenialOfService       VulnerabilityType = "DENIAL_OF_SERVICE"
	VulnerabilityTypeSupplyChain           VulnerabilityType = "SUPPLY_CHAIN"
	VulnerabilityTypeSecretExposure        VulnerabilityType = "SECRET_EXPOSURE"
	VulnerabilityTypeMemoryPoisoning       VulnerabilityType = "MEMORY_POISONING"
	VulnerabilityTypeSilentOperation       VulnerabilityType = "SILENT_OPERATION"
	VulnerabilityTypeBehaviorManipulation  VulnerabilityType = "BEHAVIOR_MANIPULATION"
	VulnerabilityTypeUnsafeAutonomy        VulnerabilityType = "UNSAFE_AUTONOMY"
	VulnerabilityTypeAPIProxyAttack        VulnerabilityType = "API_PROXY_ATTACK"
)
