//go:build ignore

// Generate public method reference and model catalogs from the checked-in Go API.
// Run from the repository root: go run scripts/generate_api_reference.go [-check].
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/doc"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const module = "github.com/cdot65/prisma-airs-go"

var packages = []struct{ path, name, title string }{
	{"aisec", "aisec", "Core SDK"},
	{"aisec/runtime", "runtime", "Runtime Security"},
	{"aisec/modelsecurity", "modelsecurity", "Model Security"},
	{"aisec/redteam", "redteam", "Red Team"},
	{"aisec/gateway", "gateway", "Gateway management"},
	{"aisec/modelsecurity/schema", "modelsecurity-schema", "Model Security schema"},
	{"aisec/redteam/schema", "redteam-schema", "Red Team schema"},
	{"aisec/gateway/schema", "gateway-schema", "Gateway schema"},
}

func main() {
	check := flag.Bool("check", false, "fail when checked-in reference differs from source")
	flag.Parse()
	if err := generate(*check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(check bool) error {
	out := "docs/reference/generated"
	if !check {
		if err := os.MkdirAll(out, 0755); err != nil {
			return err
		}
	}
	for _, pkg := range packages {
		fset := token.NewFileSet()
		parsed, err := parser.ParseDir(fset, pkg.path, func(info os.FileInfo) bool {
			return strings.HasSuffix(info.Name(), ".go") && !strings.HasSuffix(info.Name(), "_test.go")
		}, parser.ParseComments)
		if err != nil {
			return err
		}
		if len(parsed) != 1 {
			return fmt.Errorf("expected one package in %s", pkg.path)
		}
		var syntax *ast.Package
		for _, candidate := range parsed {
			syntax = candidate
		}
		api := doc.New(syntax, module+"/"+pkg.path, 0)
		var text strings.Builder
		fmt.Fprintf(&text, "---\ntitle: %s\n---\n\n", pkg.title)
		fmt.Fprintf(&text, "<!-- Generated by scripts/generate_api_reference.go; edit Go source, then regenerate. -->\n\n")
		fmt.Fprintf(&text, "Public API of `%s/%s`, generated from this SDK checkout.\n", module, pkg.path)
		fmt.Fprintf(&text, "The versioned [Go package documentation](https://pkg.go.dev/%s@v0.6.0/%s)\ncontains full declarations and source links.\n\n", module, pkg.path)
		text.WriteString("[Reference overview](../api-reference.md) explains clients, schema packages, and compatibility.\n\n")
		writeDecl := func(declaration any) error {
			var code bytes.Buffer
			if err := printer.Fprint(&code, fset, declaration); err != nil {
				return err
			}
			fmt.Fprintf(&text, "```go\n%s\n```\n\n", code.String())
			return nil
		}
		values := append(append([]*doc.Value{}, api.Consts...), api.Vars...)
		for _, kind := range api.Types {
			values = append(values, kind.Consts...)
			values = append(values, kind.Vars...)
		}
		sort.Slice(values, func(i, j int) bool { return strings.Join(values[i].Names, ",") < strings.Join(values[j].Names, ",") })
		if len(values) > 0 {
			text.WriteString("## Constants and variables\n\n")
			for _, value := range values {
				if err := writeDecl(value.Decl); err != nil {
					return err
				}
			}
		}
		functions := append([]*doc.Func{}, api.Funcs...)
		for _, kind := range api.Types {
			functions = append(functions, kind.Funcs...)
		}
		sort.Slice(functions, func(i, j int) bool { return functions[i].Name < functions[j].Name })
		if len(functions) > 0 {
			text.WriteString("## Functions\n\n")
			for _, function := range functions {
				fmt.Fprintf(&text, "### %s\n\n", function.Name)
				if function.Doc != "" {
					fmt.Fprintf(&text, "%s\n", function.Doc)
				}
				if err := writeDecl(function.Decl); err != nil {
					return err
				}
			}
		}
		for _, kind := range api.Types {
			// JSON codec methods and union accessors remain discoverable in the
			// schema catalog without making each schema page a huge code listing.
			if strings.HasSuffix(pkg.path, "/schema") || len(kind.Methods) == 0 {
				continue
			}
			fmt.Fprintf(&text, "## %s\n\n", kind.Name)
			if kind.Doc != "" {
				fmt.Fprintf(&text, "%s\n", kind.Doc)
			}
			if err := writeDecl(kind.Decl); err != nil {
				return err
			}
			for _, method := range kind.Methods {
				fmt.Fprintf(&text, "### %s.%s\n\n", kind.Name, method.Name)
				if method.Doc != "" {
					fmt.Fprintf(&text, "%s\n", method.Doc)
				}
				if err := writeDecl(method.Decl); err != nil {
					return err
				}
			}
		}
		fmt.Fprintln(&text, "## Types and models\n\nEach link opens the complete type declaration, fields, and methods.\n\n| Type | Package declaration |\n| --- | --- |")
		for _, kind := range api.Types {
			fmt.Fprintf(&text, "| `%s` | [%s](https://pkg.go.dev/%s@v0.6.0/%s#%s) |\n", kind.Name, kind.Name, module, pkg.path, kind.Name)
		}
		path := filepath.Join(out, pkg.name+".md")
		want := []byte(text.String())
		if check {
			got, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(got, want) {
				return fmt.Errorf("stale reference: %s; run go run scripts/generate_api_reference.go", path)
			}
		} else if err := os.WriteFile(path, want, 0644); err != nil {
			return err
		}
		fmt.Println(path)
	}
	return nil
}
